# Generated by Django 5.1.5 on 2025-02-01 10:15

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allifmaalusersapp', '0005_remove_user_fullnamessss'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllifmaalUsersLoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalUsersModel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('allifmaalcategory', models.CharField(blank=True, choices=[('allifmaaladmin', 'allifmaaladmin'), ('allifmaalowner', 'allifmaalowner'), ('allifmaalstaff', 'allifmaalstaff')], default='allifmaalstaff', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('allifmaalusersapp.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
