# Generated by Django 4.2.20 on 2025-05-22 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allifmaalcommonapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnowntax', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commontasksmodel',
            name='assignedto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tskempl', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
        migrations.AddField(
            model_name='commontasksmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchtasks', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commontasksmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmntskscmpn', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commontasksmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depttaskss', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commontasksmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvstasks', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commontasksmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnurtsk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonsupplierstatementsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmpsplst', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonsupplierstatementsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownspstmnt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonsupplierstatementsmodel',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supstmrl', to='allifmaalcommonapp.commonsuppliersmodel'),
        ),
        migrations.AddField(
            model_name='commonsuppliersmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchsupplr', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonsuppliersmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppusrlnm', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonsuppliersmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptsppl', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonsuppliersmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsspplr', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonsuppliersmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spplusowncrln', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonsupplierpaymentsmodel',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amesupayrlnm', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
        migrations.AddField(
            model_name='commonsupplierpaymentsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchspplpymnt', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonsupplierpaymentsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmpsupym', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonsupplierpaymentsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptspplpymnt', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonsupplierpaymentsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsspplpymnt', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonsupplierpaymentsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supymnt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonsupplierpaymentsmodel',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allifsuprln', to='allifmaalcommonapp.commonsuppliersmodel'),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchstocks', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catinvtconrlnm', to='allifmaalcommonapp.commonstockcategoriesmodel'),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnestkmpn', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptstocks', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsstocks', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='expense_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaexprelnm', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='income_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaincomerelnm', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='inventory_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coainvrelnm', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnurstkrln', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='taxrate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stktxrte', to='allifmaalcommonapp.commontaxparametersmodel'),
        ),
        migrations.AddField(
            model_name='commonstockcategoriesmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchstockcats', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonstockcategoriesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnstcatrln', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonstockcategoriesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptstockcats', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonstockcategoriesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsstockcats', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonstockcategoriesmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnurstkcat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonshareholderbankdepositsmodel',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coabnkdpasset', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
        migrations.AddField(
            model_name='commonshareholderbankdepositsmodel',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depositbankrelnefds', to='allifmaalcommonapp.commonbanksmodel'),
        ),
        migrations.AddField(
            model_name='commonshareholderbankdepositsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchbnkdpst', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonshareholderbankdepositsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depocmprlnmfd', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonshareholderbankdepositsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bnkdptmndpst', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonshareholderbankdepositsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsbnkdpst', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonshareholderbankdepositsmodel',
            name='equity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpscustrlnmdfd', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
        migrations.AddField(
            model_name='commonshareholderbankdepositsmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usrbnksrlnmedf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonsectorsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secownr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonsalariesmodel',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amsalrn', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
        migrations.AddField(
            model_name='commonsalariesmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchslrs', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonsalariesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmphrmrln', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonsalariesmodel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crrnslries', to='allifmaalcommonapp.commoncurrenciesmodel'),
        ),
        migrations.AddField(
            model_name='commonsalariesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptslrss', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonsalariesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvssalrs', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonsalariesmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrmslrnm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonsalariesmodel',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salripymtn', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
        migrations.AddField(
            model_name='commonsalariesmodel',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stafsalrnm', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
        migrations.AddField(
            model_name='commonquotesmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchqts', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonquotesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnqtsmpn', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonquotesmodel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crrncyqtes', to='allifmaalcommonapp.commoncurrenciesmodel'),
        ),
        migrations.AddField(
            model_name='commonquotesmodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allifrelatcustquote', to='allifmaalcommonapp.commoncustomersmodel'),
        ),
        migrations.AddField(
            model_name='commonquotesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptqtess', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonquotesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsqts', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonquotesmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnownqts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonquotesmodel',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qtesspymntermdd', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
        migrations.AddField(
            model_name='commonquotesmodel',
            name='salestax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='txqr', to='allifmaalcommonapp.commontaxparametersmodel'),
        ),
        migrations.AddField(
            model_name='commonquoteitemsmodel',
            name='allifquoteitemconnector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allifquoteitemrelated', to='allifmaalcommonapp.commonquotesmodel'),
        ),
        migrations.AddField(
            model_name='commonquoteitemsmodel',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allifquoteitemdescrelatednm', to='allifmaalcommonapp.commonstocksmodel'),
        ),
        migrations.AddField(
            model_name='commonpurchaseordersmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchpurchss', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonpurchaseordersmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmncmpnpo', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonpurchaseordersmodel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crrncypo', to='allifmaalcommonapp.commoncurrenciesmodel'),
        ),
        migrations.AddField(
            model_name='commonpurchaseordersmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptpurchss', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonpurchaseordersmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvspurchases', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonpurchaseordersmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnownpo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonpurchaseordersmodel',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='popymnterms', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
        migrations.AddField(
            model_name='commonpurchaseordersmodel',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suplporelnme', to='allifmaalcommonapp.commonsuppliersmodel'),
        ),
        migrations.AddField(
            model_name='commonpurchaseordermisccostsmodel',
            name='po_misc_cost_con',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pomiscrlnm', to='allifmaalcommonapp.commonpurchaseordersmodel'),
        ),
        migrations.AddField(
            model_name='commonpurchaseordermisccostsmodel',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppmiscrlnme', to='allifmaalcommonapp.commonsuppliersmodel'),
        ),
        migrations.AddField(
            model_name='commonpurchaseorderitemsmodel',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poitemrallirelnm', to='allifmaalcommonapp.commonstocksmodel'),
        ),
        migrations.AddField(
            model_name='commonpurchaseorderitemsmodel',
            name='po_item_con',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poitrelname', to='allifmaalcommonapp.commonpurchaseordersmodel'),
        ),
        migrations.AddField(
            model_name='commonpaymenttermsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brnchpymntrms', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonpaymenttermsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmppymntrms', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonpaymenttermsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymntrmsdpt', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonpaymenttermsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvspymtrm', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonpaymenttermsmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owpymnterms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonledgerentriesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmpyldgentr', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonledgerentriesmodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cstmldgentr', to='allifmaalcommonapp.commoncustomersmodel'),
        ),
        migrations.AddField(
            model_name='commonledgerentriesmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usrldgentr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonledgerentriesmodel',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empldgentr', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
        migrations.AddField(
            model_name='commonledgerentriesmodel',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sppldgentr', to='allifmaalcommonapp.commonsuppliersmodel'),
        ),
        migrations.AddField(
            model_name='commonjobsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchjobss', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonjobsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmpyjbs', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonjobsmodel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crrncjob', to='allifmaalcommonapp.commoncurrenciesmodel'),
        ),
        migrations.AddField(
            model_name='commonjobsmodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcustrelname', to='allifmaalcommonapp.commoncustomersmodel'),
        ),
        migrations.AddField(
            model_name='commonjobsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptjobs', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonjobsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsjobss', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonjobsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobsowner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonjobsmodel',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobpymtn', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
        migrations.AddField(
            model_name='commonjobitemsmodel',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemjobcon', to='allifmaalcommonapp.commonstocksmodel'),
        ),
        migrations.AddField(
            model_name='commonjobitemsmodel',
            name='jobitemconnector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemjobconrelnme', to='allifmaalcommonapp.commonjobsmodel'),
        ),
        migrations.AddField(
            model_name='commoninvoicesmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchinvc', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commoninvoicesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmninvsmpn', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commoninvoicesmodel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crrncinv', to='allifmaalcommonapp.commoncurrenciesmodel'),
        ),
        migrations.AddField(
            model_name='commoninvoicesmodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allifrelatcustinvce', to='allifmaalcommonapp.commoncustomersmodel'),
        ),
        migrations.AddField(
            model_name='commoninvoicesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptinvcs', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commoninvoicesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsinvc', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commoninvoicesmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnowninvcs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commoninvoicesmodel',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invpymnt', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
        migrations.AddField(
            model_name='commoninvoicesmodel',
            name='salestax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='txinvce', to='allifmaalcommonapp.commontaxparametersmodel'),
        ),
        migrations.AddField(
            model_name='commoninvoiceitemsmodel',
            name='allifinvitemconnector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitmsrelnm', to='allifmaalcommonapp.commoninvoicesmodel'),
        ),
        migrations.AddField(
            model_name='commoninvoiceitemsmodel',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitmstckrlnm', to='allifmaalcommonapp.commonstocksmodel'),
        ),
        migrations.AddField(
            model_name='commongeneralledgersmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glbrnchrlnm', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commongeneralledgersmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glcmprlnm', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commongeneralledgersmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gldptrlnm', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commongeneralledgersmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gldvsrln', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commongeneralledgersmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usrglrlnm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonformsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchforms', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonformsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnfrmcmp', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonformsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptforms', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonformsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsforms', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonformsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnusfrm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonexpensesmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchexpns', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonexpensesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnexpcmpn', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonexpensesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptexpns', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonexpensesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsexpns', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonexpensesmodel',
            name='equity_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coexprln', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
        migrations.AddField(
            model_name='commonexpensesmodel',
            name='expense_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaexprelnamepaytocmm', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
        migrations.AddField(
            model_name='commonexpensesmodel',
            name='funding_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaexprelnanemconcmm', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
        migrations.AddField(
            model_name='commonexpensesmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnurexpns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonexpensesmodel',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expsupprelanmeconcmm', to='allifmaalcommonapp.commonsuppliersmodel'),
        ),
        migrations.AddField(
            model_name='commonemployeesmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emplybrnch', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonemployeesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emplcomprlnmefsammnapp', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonemployeesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emplydpt', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonemployeesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emplydvs', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonemployeesmodel',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secrlmmemply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonemailsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchemil', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonemailsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emailrlnm', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonemailsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emaildptmn', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonemailsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsemil', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonemailsmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emlrlnm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commondocsformatmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docformusr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commondivisionsmodel',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dvsncmpny', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commondivisionsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owncmpndvsn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commondepartmentsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dpmntbrnch', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commondepartmentsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmpdprmnt', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commondepartmentsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dpmntdvsn', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commondepartmentsmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usrdprmnt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commondatasortsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datsortusr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commoncustomerstatementsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmpcstsmnreln', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commoncustomerstatementsmodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custstmrlnm', to='allifmaalcommonapp.commoncustomersmodel'),
        ),
        migrations.AddField(
            model_name='commoncustomerstatementsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usrcuststmnrln', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commoncustomersmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchcustmrs', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commoncustomersmodel',
            name='className',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allifmaalcommonapp.commonclassesmodel'),
        ),
        migrations.AddField(
            model_name='commoncustomersmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmncmprnm', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commoncustomersmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptcustmrs', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commoncustomersmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvscustmrs', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commoncustomersmodel',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allifmaalcommonapp.commonformsmodel'),
        ),
        migrations.AddField(
            model_name='commoncustomersmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnusrcstmrln', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commoncustomerpaymentsmodel',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allifcustpymaccrelnm', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
        migrations.AddField(
            model_name='commoncustomerpaymentsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchcustpymnt', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commoncustomerpaymentsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmpcspymnt', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commoncustomerpaymentsmodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allifcustpaymentreltedname', to='allifmaalcommonapp.commoncustomersmodel'),
        ),
        migrations.AddField(
            model_name='commoncustomerpaymentsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptcustpymnt', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commoncustomerpaymentsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvscustmrpymnt', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commoncustomerpaymentsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownrcstmpymnt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commoncurrenciesmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currnybrnch', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commoncurrenciesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmpcrrncy', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commoncurrenciesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currncydpt', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commoncurrenciesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvscrrncy', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commoncurrenciesmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owncrrncy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compscopesconn', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usrcmpscop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commoncompanydetailsmodel',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secrlmown', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commoncompanydetailsmodel',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secrlmcompcmmnapp', to='allifmaalcommonapp.commonsectorsmodel'),
        ),
        migrations.AddField(
            model_name='commonclassesmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchclss', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonclassesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnclscmpy', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonclassesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dptclss', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonclassesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsclsss', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonclassesmodel',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allifmaalcommonapp.commonformsmodel'),
        ),
        migrations.AddField(
            model_name='commonclassesmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnusrclsrln', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonchartofaccountsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaccbrnchrlnm', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonchartofaccountsmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaccmrln', to='allifmaalcommonapp.commongeneralledgersmodel'),
        ),
        migrations.AddField(
            model_name='commonchartofaccountsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmpchaccrlnm', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonchartofaccountsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaccdptrlnm', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonchartofaccountsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaccdvsrln', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonchartofaccountsmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usrchacrln', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonbranchesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brnchcmpny', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonbranchesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dvnscmpny', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonbranchesmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owncmpnbrnch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonbankwithdrawalsmodel',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coabnka', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
        migrations.AddField(
            model_name='commonbankwithdrawalsmodel',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wthdrbnkrelnm', to='allifmaalcommonapp.commonbanksmodel'),
        ),
        migrations.AddField(
            model_name='commonbankwithdrawalsmodel',
            name='bankcoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coabnkafrm', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
        migrations.AddField(
            model_name='commonbankwithdrawalsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchbnkwithdrwl', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonbankwithdrawalsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withcmprlnm', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonbankwithdrawalsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bnkdptmnwithdrwl', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonbankwithdrawalsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsbnkwithdrwl', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonbankwithdrawalsmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrusrbnkrlnmes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonbanksmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchbnk', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonbanksmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmpbnkrlnm', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonbanksmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bnkdptmn', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonbanksmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsbnk', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonbanksmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usrbnkrlnm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonassetsmodel',
            name='asset_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmassetrl', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
        migrations.AddField(
            model_name='commonassetsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchassts', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonassetsmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assetcat', to='allifmaalcommonapp.commonassetcategoriesmodel'),
        ),
        migrations.AddField(
            model_name='commonassetsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmncmpassetrln', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonassetsmodel',
            name='cost_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cstasschac', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
        migrations.AddField(
            model_name='commonassetsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptassts', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonassetsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsassts', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonassetsmodel',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asstemply', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
        migrations.AddField(
            model_name='commonassetsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnassetown', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonassetsmodel',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suplporelnmeasset', to='allifmaalcommonapp.commonsuppliersmodel'),
        ),
        migrations.AddField(
            model_name='commonassetcategoriesmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchasstscats', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonassetcategoriesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmpasstcatasst', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonassetcategoriesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptasstscats', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonassetcategoriesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsasstscats', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonassetcategoriesmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asstcatusr', to=settings.AUTH_USER_MODEL),
        ),
    ]
