# Generated by Django 5.1.5 on 2025-02-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0002_alter_commontaxparametersmodel_taxname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commondivisionsmodel',
            options={'ordering': ['-division', 'address']},
        ),
        migrations.AlterField(
            model_name='commondivisionsmodel',
            name='division',
            field=models.CharField(blank=True, help_text='Enter a book genre (e.g. Science Fiction, French Poetry', max_length=50, null=True),
        ),
    ]
