# Generated by Django 4.2.20 on 2025-08-01 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonservicesmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonservicesmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonservicesmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonservicesmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonservicesmodel',
            name='operation_term',
        ),
        migrations.RemoveField(
            model_name='commonservicesmodel',
            name='operation_year',
        ),
        migrations.RemoveField(
            model_name='commonservicesmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonservicesmodel',
            name='program',
        ),
        migrations.RemoveField(
            model_name='commonservicesmodel',
            name='unit_of_measure',
        ),
        migrations.RemoveField(
            model_name='commonservicesmodel',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='commoncompanyscopemodel',
            name='scope_assumptions',
        ),
        migrations.RemoveField(
            model_name='commoncompanyscopemodel',
            name='scope_constraints',
        ),
        migrations.RemoveField(
            model_name='commoncompanyscopemodel',
            name='scope_exclusions',
        ),
        migrations.RemoveField(
            model_name='commoncompanyscopemodel',
            name='scope_resources',
        ),
        migrations.RemoveField(
            model_name='commoncompanyscopemodel',
            name='scope_risks',
        ),
        migrations.RemoveField(
            model_name='commoncompanyscopemodel',
            name='scope_stakeholders',
        ),
        migrations.RemoveField(
            model_name='commoncompanyscopemodel',
            name='scope_type',
        ),
        migrations.DeleteModel(
            name='CommonProgramsModel',
        ),
        migrations.DeleteModel(
            name='CommonServicesModel',
        ),
    ]
