# Generated by Django 4.2.20 on 2025-07-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonapproversmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonassetcategoriesmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonassetsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonbanksmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonbankwithdrawalsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commoncategoriesmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonchartofaccountsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commoncodesmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commoncompanyscopemodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commoncreditnoteitemsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commoncreditnotesmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commoncurrenciesmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commoncustomerpaymentsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commoncustomersmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commoncustomerstatementsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonemailsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonemployeesmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonexpensesmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commongeneralledgersmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commoninvoiceitemsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commoninvoicesmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonjobitemsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonjobsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonledgerentriesmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonpaymenttermsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonprogramsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonprogressmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonpurchaseorderitemsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonpurchaseordermisccostsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonpurchaseordersmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonquoteitemsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonquotesmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonsalariesmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonservicesmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonshareholderbankdepositsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonspacebookingitemsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonspacesmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonspaceunitsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonstocksmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonstocktransferorderitemsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonstocktransferordersmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonsupplierpaymentsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonsuppliersmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonsupplierstatementsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonsuppliertaxparametersmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commontasksmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commontransactionitemsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commontransactionsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commontransititemsmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commontransitmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commonunitsmodel',
            options={'ordering': ['-date']},
        ),
    ]
