# Generated by Django 4.2.20 on 2025-06-09 08:04

import allifmaalcommonapp.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0002_alter_commonwarehousesmodel_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonoperationyearsmodel',
            name='comments',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonoperationyearsmodel',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AlterField(
            model_name='commonoperationyearsmodel',
            name='is_current',
            field=models.CharField(blank=True, choices=[('Current', 'Current'), ('Passed', 'Passed'), ('Future', 'Future')], default='Current', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonoperationyearsmodel',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AlterField(
            model_name='commonoperationyearsmodel',
            name='year',
            field=models.CharField(blank=True, default='Operation Year', help_text='e.g., 2023-2024', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonoperationyeartermsmodel',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AlterField(
            model_name='commonoperationyeartermsmodel',
            name='is_current',
            field=models.CharField(blank=True, choices=[('Current', 'Current'), ('Passed', 'Passed'), ('Future', 'Future')], default='Current', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonoperationyeartermsmodel',
            name='operation_year',
            field=models.ForeignKey(blank=True, default=allifmaalcommonapp.models.get_default_operation_year, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termsyear', to='allifmaalcommonapp.commonoperationyearsmodel'),
        ),
        migrations.AlterField(
            model_name='commonoperationyeartermsmodel',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
