# Generated by Django 4.2.20 on 2025-09-06 15:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoncountriesmodel',
            name='notes',
        ),
        migrations.AddField(
            model_name='commoncountriesmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commoncountriesmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commoncountriesmodel',
            name='code',
            field=models.CharField(blank=True, default='Code', help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commoncountriesmodel',
            name='comments',
            field=models.TextField(blank=True, default='Comments', null=True),
        ),
        migrations.AddField(
            model_name='commoncountriesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commoncountriesmodel',
            name='delete_status',
            field=models.CharField(blank=True, choices=[('Undeletable', 'Undeletable'), ('Deletable', 'Deletable')], default='Deletable', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='commoncountriesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commoncountriesmodel',
            name='description',
            field=models.TextField(blank=True, default='Description', null=True),
        ),
        migrations.AddField(
            model_name='commoncountriesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commoncountriesmodel',
            name='ends',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='commoncountriesmodel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='commoncountriesmodel',
            name='number',
            field=models.CharField(blank=True, default='#No', help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commoncountriesmodel',
            name='operation_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonoperationyeartermsmodel'),
        ),
        migrations.AddField(
            model_name='commoncountriesmodel',
            name='operation_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonoperationyearsmodel'),
        ),
        migrations.AddField(
            model_name='commoncountriesmodel',
            name='priority',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Urgent', 'Urgent')], default='Normal', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commoncountriesmodel',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commoncountriesmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commoncountriesmodel',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='reference', help_text='An optional identifier from an external system or an internal reference code.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commoncountriesmodel',
            name='starts',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='commoncountriesmodel',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commoncountriesmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='commoncountriesmodel',
            name='name',
            field=models.CharField(blank=True, default='Name', max_length=50, null=True),
        ),
    ]
