# Generated by Django 4.2.20 on 2025-08-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncompanydetailsmodel',
            name='use_subdomain',
            field=models.BooleanField(default=True),
        ),
    ]
