# Generated by Django 4.2.20 on 2025-08-12 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='asset_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmassetrl', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='cost_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cstasschac', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
    ]
