# Generated by Django 4.2.20 on 2025-05-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commondatasortsmodel',
            name='name',
            field=models.CharField(default='asc', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='commondocsformatmodel',
            name='name',
            field=models.CharField(default='pdf', max_length=30, unique=True),
        ),
    ]
