# Generated by Django 4.2.20 on 2025-08-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0003_commoncompanydetailsmodel_use_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonbranchesmodel',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='reference', help_text='An optional identifier from an external system or an internal reference code.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commoncompanydetailsmodel',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='reference', help_text='An optional identifier from an external system or an internal reference code.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commondepartmentsmodel',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='reference', help_text='An optional identifier from an external system or an internal reference code.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commondivisionsmodel',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='reference', help_text='An optional identifier from an external system or an internal reference code.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commonoperationyearsmodel',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='reference', help_text='An optional identifier from an external system or an internal reference code.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commonoperationyeartermsmodel',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='reference', help_text='An optional identifier from an external system or an internal reference code.', max_length=100, null=True),
        ),
    ]
