# Generated by Django 5.1.5 on 2025-02-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0003_alter_commondivisionsmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commondivisionsmodel',
            name='comments',
            field=models.TextField(blank=True, help_text='Enter a brief description of the division', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commondivisionsmodel',
            name='division',
            field=models.CharField(blank=True, help_text='Enter division name', max_length=50, null=True),
        ),
    ]
