# Generated by Django 4.2.20 on 2025-06-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0003_alter_commoncustomerpaymentsmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoncustomerpaymentsmodel',
            name='status',
        ),
    ]
