# Generated by Django 4.2.20 on 2025-05-23 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0003_alter_commondatasortsmodel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonsalariesmodel',
            name='payment_terms',
        ),
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scopebrcnh', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scopdptm', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvscpe', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AlterField(
            model_name='commonassetcategoriesmodel',
            name='comments',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonassetcategoriesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmpasstcatasst', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmncmpassetrln', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asstpymnterms', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='years_depreciated',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonbanksmodel',
            name='comments',
            field=models.CharField(blank=True, default='comment', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commonbanksmodel',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonbankwithdrawalsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withcmprlnm', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commonbankwithdrawalsmodel',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonbranchesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvnscmpny', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AlterField(
            model_name='commonbranchesmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owncmpnbrnch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commonchartofaccountsmodel',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonclassesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dptclss', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AlterField(
            model_name='commoncompanydetailsmodel',
            name='companyuid',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commoncompanydetailsmodel',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secrlmcompcmmnapp', to='allifmaalcommonapp.commonsectorsmodel'),
        ),
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compscopesconn', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commoncontactsmodel',
            name='email',
            field=models.EmailField(default='email', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commoncontactsmodel',
            name='name',
            field=models.CharField(default='name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commoncontactsmodel',
            name='subject',
            field=models.CharField(default='subject', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commoncurrenciesmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currnybrnch', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AlterField(
            model_name='commoncurrenciesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmpcrrncy', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commoncurrenciesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currncydpt', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AlterField(
            model_name='commoncustomerpaymentsmodel',
            name='comments',
            field=models.CharField(blank=True, default='comment', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commoncustomerpaymentsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmpcspymnt', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commoncustomerpaymentsmodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allifcustpaymentreltedname', to='allifmaalcommonapp.commoncustomersmodel'),
        ),
        migrations.AlterField(
            model_name='commoncustomerpaymentsmodel',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custmrpymnterms', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
        migrations.AlterField(
            model_name='commoncustomersmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmncmprnm', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commoncustomersmodel',
            name='customerslug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commoncustomersmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commoncustomersmodel',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commoncustomersmodel',
            name='paymentType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custmerrpymntrms', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
        migrations.AlterField(
            model_name='commoncustomerstatementsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmpcstsmnreln', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commoncustomerstatementsmodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custstmrlnm', to='allifmaalcommonapp.commoncustomersmodel'),
        ),
        migrations.AlterField(
            model_name='commondepartmentsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpmntbrnch', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AlterField(
            model_name='commondepartmentsmodel',
            name='departmentslug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commondepartmentsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpmntdvsn', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AlterField(
            model_name='commondivisionsmodel',
            name='divisionslug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commondivisionsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owncmpndvsn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commonemailsmodel',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commonemailsmodel',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commonemployeesmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplybrnch', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AlterField(
            model_name='commonemployeesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplydpt', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AlterField(
            model_name='commonemployeesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplydvs', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AlterField(
            model_name='commonemployeesmodel',
            name='lastName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonemployeesmodel',
            name='staffNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonemployeesmodel',
            name='stffslug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonexpensesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmnexpcmpn', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commonexpensesmodel',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonexpensesmodel',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expnspymnterms', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
        migrations.AlterField(
            model_name='commonformsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmnfrmcmp', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commongeneralledgersmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glcmprlnm', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='comments',
            field=models.CharField(blank=True, default='Invoice Comments', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmninvsmpn', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='description',
            field=models.CharField(blank=True, default='Invoice', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='invoice_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crrncinvoice', to='allifmaalcommonapp.commoncurrenciesmodel'),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='invoice_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invpymnterms', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
        migrations.AlterField(
            model_name='commonjobsmodel',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commonjobsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmpyjbs', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commonjobsmodel',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonledgerentriesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmpyldgentr', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commonledgerentriesmodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cstmldgentr', to='allifmaalcommonapp.commoncustomersmodel'),
        ),
        migrations.AlterField(
            model_name='commonledgerentriesmodel',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empldgentr', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
        migrations.AlterField(
            model_name='commonledgerentriesmodel',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sppldgentr', to='allifmaalcommonapp.commonsuppliersmodel'),
        ),
        migrations.AlterField(
            model_name='commonpaymenttermsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchpymntrms', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AlterField(
            model_name='commonpaymenttermsmodel',
            name='comments',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonpaymenttermsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmppymntrms', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commonpaymenttermsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymntrmsdpt', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AlterField(
            model_name='commonpurchaseordermisccostsmodel',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseordersmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmncmpnpo', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commonquotesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmnqtsmpn', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commonsalariesmodel',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonsalariesmodel',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salripymtn', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
        migrations.AlterField(
            model_name='commonsectorsmodel',
            name='name',
            field=models.CharField(default='Sector Name', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='commonshareholderbankdepositsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depocmprlnmfd', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commonshareholderbankdepositsmodel',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonstockcategoriesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmnstcatrln', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmnestkmpn', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='partNumber',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='commonsupplierpaymentsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmpsupym', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commonsupplierpaymentsmodel',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplrpymnterms', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
        migrations.AlterField(
            model_name='commonsuppliersmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonsuppliersmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppusrlnm', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commonsuppliersmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonsuppliersmodel',
            name='turnover',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonsupplierstatementsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmpsplst', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commonsupplierstatementsmodel',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supstmrl', to='allifmaalcommonapp.commonsuppliersmodel'),
        ),
        migrations.AlterField(
            model_name='commontasksmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmntskscmpn', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commontasksmodel',
            name='task',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commontaxparametersmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='txpbrcnh', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AlterField(
            model_name='commontaxparametersmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmntaxcmp', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commontaxparametersmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='txprdptm', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AlterField(
            model_name='commontaxparametersmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvstxprm', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
    ]
