# Generated by Django 4.2.20 on 2025-08-01 06:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0003_remove_commonservicesmodel_branch_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommonAuditLogsModel',
            new_name='CommonLogsModel',
        ),
    ]
