# Generated by Django 4.2.20 on 2025-08-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0004_rename_commonauditlogsmodel_commonlogsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonlogsmodel',
            name='user',
        ),
    ]
