# Generated by Django 4.2.20 on 2025-06-09 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0004_alter_commonoperationyearsmodel_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonprogramsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_programms', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
    ]
