# Generated by Django 4.2.20 on 2025-07-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0004_alter_commonapproversmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commontaxparametersmodel',
            name='tax_assumptions',
        ),
        migrations.RemoveField(
            model_name='commontaxparametersmodel',
            name='tax_constraints',
        ),
        migrations.RemoveField(
            model_name='commontaxparametersmodel',
            name='tax_exclusions',
        ),
        migrations.RemoveField(
            model_name='commontaxparametersmodel',
            name='tax_resources',
        ),
        migrations.RemoveField(
            model_name='commontaxparametersmodel',
            name='tax_risks',
        ),
        migrations.RemoveField(
            model_name='commontaxparametersmodel',
            name='tax_stakeholders',
        ),
    ]
