# Generated by Django 4.2.20 on 2025-08-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0004_commonstaffcategoriesmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonemployeesmodel',
            old_name='category',
            new_name='staff_cat',
        ),
    ]
