# Generated by Django 4.2.20 on 2025-06-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0004_remove_commonapproversmodel_is_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonapproversmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonapproversmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonassetcategoriesmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonassetcategoriesmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonbanksmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonbanksmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonbankwithdrawalsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonbankwithdrawalsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commoncategoriesmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncategoriesmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonchartofaccountsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonchartofaccountsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commoncodesmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncodesmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commoncreditnoteitemsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncreditnoteitemsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commoncreditnotesmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncreditnotesmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commoncurrenciesmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncurrenciesmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commoncustomerpaymentsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncustomerpaymentsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commoncustomersmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncustomersmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commoncustomerstatementsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncustomerstatementsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonemailsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonemailsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonemployeesmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonemployeesmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonexpensesmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonexpensesmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commongeneralledgersmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commongeneralledgersmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commoninvoiceitemsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoninvoiceitemsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonjobitemsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonjobitemsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonjobsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonjobsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonledgerentriesmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonledgerentriesmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonpaymenttermsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonpaymenttermsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonprogramsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonprogramsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonprogressmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonprogressmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseorderitemsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseorderitemsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseordermisccostsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseordermisccostsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseordersmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseordersmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonquoteitemsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonquoteitemsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonquotesmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonquotesmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonsalariesmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonsalariesmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonservicesmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonservicesmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonshareholderbankdepositsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonshareholderbankdepositsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonspacebookingitemsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacebookingitemsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonspaceitemsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonspaceitemsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonspaceunitsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonspaceunitsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonstocktransferorderitemsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonstocktransferorderitemsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonstocktransferordersmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonstocktransferordersmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonsupplierpaymentsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonsupplierpaymentsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonsuppliersmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonsuppliersmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonsupplierstatementsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonsupplierstatementsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonsuppliertaxparametersmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonsuppliertaxparametersmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commontasksmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commontasksmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commontaxparametersmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commontaxparametersmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commontransactionitemsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commontransactionitemsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commontransactionsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commontransactionsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commontransititemsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commontransititemsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commontransitmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commontransitmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonunitsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonunitsmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True, unique=True),
        ),
    ]
