# Generated by Django 4.2.20 on 2025-06-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0004_remove_commoncustomerpaymentsmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncustomerpaymentsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting', 'waiting'), ('posted', 'posted')], default='waiting', max_length=200, null=True),
        ),
    ]
