# Generated by Django 4.2.20 on 2025-08-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0004_commonbranchesmodel_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonbranchesmodel',
            name='priority',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Urgent', 'Urgent')], default='Normal', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commoncompanydetailsmodel',
            name='priority',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Urgent', 'Urgent')], default='Normal', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commondepartmentsmodel',
            name='priority',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Urgent', 'Urgent')], default='Normal', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commondivisionsmodel',
            name='priority',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Urgent', 'Urgent')], default='Normal', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commonoperationyearsmodel',
            name='priority',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Urgent', 'Urgent')], default='Normal', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commonoperationyeartermsmodel',
            name='priority',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Urgent', 'Urgent')], default='Normal', max_length=50, null=True),
        ),
    ]
