# Generated by Django 5.1.5 on 2025-02-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0004_commondivisionsmodel_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url_name', models.CharField(max_length=200)),
                ('url_params', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
