# Generated by Django 4.2.20 on 2025-05-24 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0004_remove_commonsalariesmodel_payment_terms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonSupplierTaxParametersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxname', models.CharField(blank=True, max_length=30, null=True)),
                ('taxdescription', models.CharField(blank=True, max_length=30, null=True)),
                ('taxtype', models.CharField(blank=True, choices=[('Default', 'Default'), ('Dynamic', 'Dynamic')], max_length=30)),
                ('taxrate', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplirtxpbrcnh', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplrcmntaxcmp', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplirtxprdptm', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplirdvstxprm', to='allifmaalcommonapp.commondivisionsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplrcmnowntax', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='suppliertaxrate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplrstktxrte', to='allifmaalcommonapp.commonsuppliertaxparametersmodel'),
        ),
    ]
