# Generated by Django 4.2.20 on 2025-06-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0005_commoncustomerpaymentsmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonspacesmodel',
            name='inventory_account',
        ),
    ]
