# Generated by Django 4.2.20 on 2025-08-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0005_remove_commonlogsmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonemployeesmodel',
            name='slgfld',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
