# Generated by Django 4.2.20 on 2025-05-24 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0005_commonsuppliertaxparametersmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonpurchaseordersmodel',
            name='taxrate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sppltxrt', to='allifmaalcommonapp.commonsuppliertaxparametersmodel'),
        ),
    ]
