# Generated by Django 4.2.20 on 2025-07-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0005_remove_commontaxparametersmodel_tax_assumptions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoncustomersmodel',
            name='chronic_conditions',
        ),
        migrations.RemoveField(
            model_name='commoncustomersmodel',
            name='client_status',
        ),
        migrations.RemoveField(
            model_name='commoncustomersmodel',
            name='course_category',
        ),
        migrations.RemoveField(
            model_name='commoncustomersmodel',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='commoncustomersmodel',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='commoncustomersmodel',
            name='known_allergies',
        ),
        migrations.RemoveField(
            model_name='commoncustomersmodel',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='commoncustomersmodel',
            name='term',
        ),
        migrations.AddField(
            model_name='commoncustomersmodel',
            name='document_number',
            field=models.CharField(blank=True, help_text='Unique ID for guest', max_length=100, null=True, unique=True),
        ),
    ]
