# Generated by Django 4.2.20 on 2025-08-08 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0005_commonbranchesmodel_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonbranchesmodel',
            name='can_delete',
            field=models.CharField(blank=True, choices=[('Undeletable', 'Undeletable'), ('Deletable', 'Deletable')], default='Undeletable', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncompanydetailsmodel',
            name='can_delete',
            field=models.CharField(blank=True, choices=[('Undeletable', 'Undeletable'), ('Deletable', 'Deletable')], default='Undeletable', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commondepartmentsmodel',
            name='can_delete',
            field=models.CharField(blank=True, choices=[('Undeletable', 'Undeletable'), ('Deletable', 'Deletable')], default='Undeletable', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commondivisionsmodel',
            name='can_delete',
            field=models.CharField(blank=True, choices=[('Undeletable', 'Undeletable'), ('Deletable', 'Deletable')], default='Undeletable', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonoperationyearsmodel',
            name='can_delete',
            field=models.CharField(blank=True, choices=[('Undeletable', 'Undeletable'), ('Deletable', 'Deletable')], default='Undeletable', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonoperationyeartermsmodel',
            name='can_delete',
            field=models.CharField(blank=True, choices=[('Undeletable', 'Undeletable'), ('Deletable', 'Deletable')], default='Undeletable', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonoperationyeartermsmodel',
            name='operation_term',
            field=models.CharField(blank=True, default='Operation Term', help_text='e.g., 2023-2024', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonoperationyeartermsmodel',
            name='operation_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_operation_year', to='allifmaalcommonapp.commonoperationyearsmodel'),
        ),
    ]
