# Generated by Django 4.2.20 on 2025-07-01 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('allifmaalcommonapp', '0005_alter_commonapproversmodel_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commontaxparametersmodel',
            options={'permissions': [('view_tax_parameter', 'Can view tax parameter'), ('add_tax_parameter', 'Can add tax parameter'), ('change_tax_parameter', 'Can change tax parameter'), ('delete_tax_parameter', 'Can delete tax parameter')]},
        ),
        migrations.AlterField(
            model_name='commontaxparametersmodel',
            name='taxrate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commontaxparametersmodel',
            name='taxtype',
            field=models.CharField(blank=True, choices=[('Default', 'Default'), ('Dynamic', 'Dynamic')], default='Default', max_length=30),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_type', models.CharField(max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('change_message', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-action_time'],
                'permissions': [('view_audit_log', 'Can view audit log entries')],
            },
        ),
    ]
