# Generated by Django 5.1.5 on 2025-02-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0005_templatelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonContactsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='name', max_length=60, null=True)),
                ('subject', models.CharField(blank=True, default='subject', max_length=20, null=True)),
                ('email', models.CharField(blank=True, default='email', max_length=30, null=True)),
                ('message', models.CharField(blank=True, default='message', max_length=255, null=True)),
            ],
        ),
    ]
