# Generated by Django 4.2.20 on 2025-06-09 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0005_alter_commonprogramsmodel_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonoperationyeartermsmodel',
            name='operation_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termsyear', to='allifmaalcommonapp.commonoperationyearsmodel'),
        ),
    ]
