# Generated by Django 4.2.20 on 2025-08-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0005_rename_category_commonemployeesmodel_staff_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonapproversmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonassessmentsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonassetsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonbanksmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonbankwithdrawalsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commoncategoriesmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonchartofaccountsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commoncodesmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commoncreditnoteitemsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commoncreditnotesmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commoncurrenciesmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commoncustomerpaymentsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commoncustomersmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commoncustomerstatementsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonemailsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonemployeesmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonexpensesmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commongeneralledgersmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commoninvoiceitemsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commoninvoicesmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonjobitemsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonjobsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonledgerentriesmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonlogsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonpaymenttermsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonprogressmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonpurchaseorderitemsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonpurchaseordermisccostsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonpurchaseordersmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonquoteitemsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonquotesmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonresultsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonsalariesmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonshareholderbankdepositsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonspacebookingitemsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonspaceitemsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonspacesmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonspaceunitsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonstaffcategoriesmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonstocktransferorderitemsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonstocktransferordersmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonsupplierpaymentsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonsuppliersmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonsupplierstatementsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonsuppliertaxparametersmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commontasksmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commontransactionitemsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commontransactionsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commontransitmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commonunitsmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonassessmentsmodel',
            name='test_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Processing', 'Processing'), ('Available', 'Available'), ('Ordered', 'Ordered'), ('Pending', 'Pending'), ('Active', 'Active'), ('Emergency', 'Emergency'), ('Completed', 'Completed'), ('Collected', 'Collected'), ('Cancelled', 'Cancelled'), ('On_Hold', 'On Hold'), ('Passed', 'Passed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Validated', 'Validated'), ('Preparing', 'Preparing'), ('Lost', 'Lost')], default='Ordered', help_text='Current status of the lab order.', max_length=50),
        ),
    ]
