# Generated by Django 4.2.20 on 2025-06-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0006_remove_commonspacesmodel_inventory_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonspacesmodel',
            name='area_sqft',
        ),
        migrations.RemoveField(
            model_name='commonspacesmodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='commonspacesmodel',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='commonspacesmodel',
            name='rental_price',
        ),
        migrations.RemoveField(
            model_name='commonspacesmodel',
            name='unit_type',
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='amenities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='max_occupancy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='number_of_bathrooms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='number_of_bedrooms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
