# Generated by Django 4.2.20 on 2025-08-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0006_commonapproversmodel_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonapproversmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonassessmentsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonbanksmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonbankwithdrawalsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commoncategoriesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonchartofaccountsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commoncodesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commoncreditnoteitemsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commoncreditnotesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commoncurrenciesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commoncustomerpaymentsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commoncustomersmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commoncustomerstatementsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commondatasortsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commondocsformatmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonemailsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonemployeesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonexpensesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commongeneralledgersmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commoninvoiceitemsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonjobitemsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonjobsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonledgerentriesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonlogsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonpaymenttermsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonprogressmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseorderitemsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseordermisccostsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseordersmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonquoteitemsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonquotesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonresultsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonsalariesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonsectorsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonshareholderbankdepositsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacebookingitemsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonspaceitemsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Under Maintenance'), ('Construction', 'Under Construction'), ('Sale', 'For Sale'), ('Rent', 'For Rent'), ('Development', 'For Development'), ('Pending', 'Pending'), ('Sold', 'Sold'), ('Rented', 'Rented'), ('Cancelled', 'Cancelled')], default='AVAIL', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonspaceunitsmodel',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Under Maintenance'), ('Construction', 'Under Construction'), ('Sale', 'For Sale'), ('Rent', 'For Rent'), ('Development', 'For Development'), ('Pending', 'Pending'), ('Sold', 'Sold'), ('Rented', 'Rented'), ('Cancelled', 'Cancelled')], default='AVAIL', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='commonspaceunitsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonstaffcategoriesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonstocktransferorderitemsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonstocktransferordersmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonsupplierpaymentsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonsuppliersmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonsupplierstatementsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonsuppliertaxparametersmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commontasksmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commontaxparametersmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commontransactionitemsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commontransactionsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commontransititemsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commontransitmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonunitsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
    ]
