# Generated by Django 4.2.20 on 2025-06-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0006_alter_commonoperationyeartermsmodel_operation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonoperationyeartermsmodel',
            name='ahmed',
            field=models.CharField(blank=True, help_text='e.g., Term 1, Semester A', max_length=100, null=True),
        ),
    ]
