# Generated by Django 4.2.20 on 2025-07-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0006_remove_commoncustomersmodel_chronic_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncustomersmodel',
            name='document_number',
            field=models.CharField(blank=True, help_text='Unique ID for guest', max_length=100, null=True),
        ),
    ]
