# Generated by Django 5.1.5 on 2025-02-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0006_commoncontactsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncontactsmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='commoncontactsmodel',
            name='email',
            field=models.CharField(default='email', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncontactsmodel',
            name='message',
            field=models.CharField(default='message', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commoncontactsmodel',
            name='name',
            field=models.CharField(default='name', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='commoncontactsmodel',
            name='subject',
            field=models.CharField(default='subject', max_length=20, null=True),
        ),
    ]
