# Generated by Django 4.2.20 on 2025-05-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0006_commonpurchaseordersmodel_taxrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonshareholderbankdepositsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting', 'waiting'), ('posted', 'posted')], default='waiting', max_length=20, null=True),
        ),
    ]
