# Generated by Django 4.2.20 on 2025-05-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0007_commonshareholderbankdepositsmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonchartofaccountsmodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
    ]
