# Generated by Django 4.2.20 on 2025-08-31 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0007_alter_commonapproversmodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonspaceunitsmodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speces_units_customer', to='allifmaalcommonapp.commoncustomersmodel'),
        ),
    ]
