# Generated by Django 4.2.20 on 2025-03-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0007_commoncontactsmodel_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commondepartmentsmodel',
            old_name='description',
            new_name='department',
        ),
    ]
