# Generated by Django 4.2.20 on 2025-06-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0007_remove_commonspacesmodel_area_sqft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonspacesmodel',
            name='number_of_units',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
