# Generated by Django 4.2.20 on 2025-07-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0007_alter_commoncustomersmodel_document_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonassetsmodel',
            name='equipment_name',
        ),
        migrations.RemoveField(
            model_name='commonassetsmodel',
            name='equipment_status',
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='years_depreciated',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='CommonAssetCategoriesModel',
        ),
    ]
