# Generated by Django 4.2.20 on 2025-06-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0007_commonoperationyeartermsmodel_ahmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonoperationyeartermsmodel',
            name='operation_year',
        ),
    ]
