# Generated by Django 4.2.20 on 2025-09-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0008_commonspaceunitsmodel_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonspacesmodel',
            name='taken_units',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
