# Generated by Django 4.2.20 on 2025-03-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0008_rename_description_commondepartmentsmodel_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='commondepartmentsmodel',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commondepartmentsmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commondepartmentsmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commondepartmentsmodel',
            name='pobox',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
