# Generated by Django 4.2.20 on 2025-07-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0008_remove_commonassetsmodel_equipment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commontransactionsmodel',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
    ]
