# Generated by Django 4.2.20 on 2025-06-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0008_commonspacesmodel_number_of_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='current_status',
            field=models.CharField(blank=True, choices=[('AVAIL', 'Available'), ('OCC', 'Occupied'), ('MAINT', 'Maintenance'), ('DIRTY', 'Dirty'), ('SALE', 'For Sale'), ('RENT', 'For Rent'), ('DEV', 'For Development'), ('PEND', 'Pending'), ('SOLD', 'Sold'), ('RENTED', 'Rented'), ('OFFMKT', 'Off Market'), ('CANC', 'Cancelled')], default='AVAIL', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='space_floor',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29')], null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='space_type',
            field=models.CharField(blank=True, choices=[('AVAIL', 'Available'), ('OCC', 'Occupied'), ('MAINT', 'Maintenance'), ('DIRTY', 'Dirty'), ('SALE', 'For Sale'), ('RENT', 'For Rent'), ('DEV', 'For Development'), ('PEND', 'Pending'), ('SOLD', 'Sold'), ('RENTED', 'Rented'), ('OFFMKT', 'Off Market'), ('CANC', 'Cancelled')], default='AVAIL', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonspaceunitsmodel',
            name='current_status',
            field=models.CharField(blank=True, choices=[('AVAIL', 'Available'), ('OCC', 'Occupied'), ('MAINT', 'Maintenance'), ('DIRTY', 'Dirty'), ('SALE', 'For Sale'), ('RENT', 'For Rent'), ('DEV', 'For Development'), ('PEND', 'Pending'), ('SOLD', 'Sold'), ('RENTED', 'Rented'), ('OFFMKT', 'Off Market'), ('CANC', 'Cancelled')], default='AVAIL', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='commonspaceunitsmodel',
            name='space_floor',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29')], null=True),
        ),
        migrations.AlterField(
            model_name='commonspaceunitsmodel',
            name='space_type',
            field=models.CharField(blank=True, choices=[('AVAIL', 'Available'), ('OCC', 'Occupied'), ('MAINT', 'Maintenance'), ('DIRTY', 'Dirty'), ('SALE', 'For Sale'), ('RENT', 'For Rent'), ('DEV', 'For Development'), ('PEND', 'Pending'), ('SOLD', 'Sold'), ('RENTED', 'Rented'), ('OFFMKT', 'Off Market'), ('CANC', 'Cancelled')], default='AVAIL', max_length=10, null=True),
        ),
    ]
