# Generated by Django 4.2.20 on 2025-05-25 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0008_alter_commonchartofaccountsmodel_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonApprovalPolicyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('CreditNote', 'Credit Note'), ('TransferOrder', 'Transfer Order')], max_length=50)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_policies', to='allifmaalcommonapp.commoncompanydetailsmodel')),
            ],
            options={
                'verbose_name_plural': 'Approval Policies',
                'unique_together': {('company', 'document_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CommonWarehousesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchswrhss', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmpnwhrn', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptswrhss', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvswrhs', to='allifmaalcommonapp.commondivisionsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wrhsown', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommonStockTransferOrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchintcmpstcktrnsfrs', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmpnintcmpstcktrnsfrs', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptintcmpstcktrnsfrs', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsintcmpstcktrnsfrs', to='allifmaalcommonapp.commondivisionsmodel')),
                ('from_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frmintcmpstcktrnsfrs', to='allifmaalcommonapp.commonwarehousesmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intcmpstcktrnsfrsown', to=settings.AUTH_USER_MODEL)),
                ('to_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tointcmpstcktrnsfrs', to='allifmaalcommonapp.commonwarehousesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommonStockTransferOrderItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=30, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stcktrnsfordrln', to='allifmaalcommonapp.commonstocksmodel')),
                ('trans_ord_items_con', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poitrelname', to='allifmaalcommonapp.commonstocktransferordersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommonCreditNotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_date', models.DateField(default=django.utils.timezone.now)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('credit_note_number', models.CharField(max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('reasons', models.CharField(max_length=100)),
                ('status', models.CharField(default='Draft', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmpnycrdnt', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cstmcrdtnot', to='allifmaalcommonapp.commoncustomersmodel')),
                ('original_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credtnorgninv', to='allifmaalcommonapp.commoninvoicesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommonCreditNoteItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crdntitems', to='allifmaalcommonapp.commoncreditnotesmodel')),
                ('items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allifmaalcommonapp.commonstocksmodel')),
                ('return_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allifmaalcommonapp.commonwarehousesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommonApproversModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver_groups', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('members', models.ManyToManyField(related_name='approval_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CommonApprovalStepsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField()),
                ('approval_method', models.CharField(choices=[('Any', 'Any member approves'), ('All', 'All members approve')], default='Any', max_length=50)),
                ('approver_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='allifmaalcommonapp.commonapproversmodel')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='allifmaalcommonapp.commonapprovalpolicymodel')),
            ],
            options={
                'ordering': ['step_order'],
                'unique_together': {('policy', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='CommonApprovalRequestsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allifmaalcommonapp.commonapprovalstepsmodel')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_approvals', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='allifmaalcommonapp.commonapprovalpolicymodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommonApprovalLogsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned for Rework')], max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='allifmaalcommonapp.commonapprovalrequestsmodel')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allifmaalcommonapp.commonapprovalstepsmodel')),
            ],
        ),
    ]
