# Generated by Django 4.2.20 on 2025-03-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0009_commondepartmentsmodel_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commondepartmentsmodel',
            name='comments',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
