# Generated by Django 4.2.20 on 2025-09-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0009_commonspacesmodel_taken_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonspacesmodel',
            name='occupancy_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Occupancy rate as a percentage', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='number_of_units',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='taken_units',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
