# Generated by Django 4.2.20 on 2025-06-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0009_alter_commonspacesmodel_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonspaceunitsmodel',
            name='area_sqft',
        ),
        migrations.RemoveField(
            model_name='commonspaceunitsmodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='commonspaceunitsmodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='commonspaceunitsmodel',
            name='is_available',
        ),
        migrations.AddField(
            model_name='commonspaceunitsmodel',
            name='area_sqm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commonspaceunitsmodel',
            name='rooms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commonspaceunitsmodel',
            name='unitcost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commonspaceunitsmodel',
            name='unitprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commonspaceunitsmodel',
            name='washrooms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='amenities',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance'), ('Sale', 'For Sale'), ('Rent', 'For Rent'), ('Development', 'For Development'), ('Pending', 'Pending'), ('Sold', 'Sold'), ('Rented', 'Rented'), ('Cancelled', 'Cancelled')], default='AVAIL', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='space_type',
            field=models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Land', 'Land'), ('Mixed-Use', 'Mixed-Use')], default='AVAIL', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='commonspaceunitsmodel',
            name='amenities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commonspaceunitsmodel',
            name='capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commonspaceunitsmodel',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance'), ('Sale', 'For Sale'), ('Rent', 'For Rent'), ('Development', 'For Development'), ('Pending', 'Pending'), ('Sold', 'Sold'), ('Rented', 'Rented'), ('Cancelled', 'Cancelled')], default='AVAIL', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='commonspaceunitsmodel',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='commonspaceunitsmodel',
            name='max_occupancy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commonspaceunitsmodel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commonspaceunitsmodel',
            name='space_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='commonspaceunitsmodel',
            name='space_type',
            field=models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Land', 'Land'), ('Mixed-Use', 'Mixed-Use')], default='AVAIL', max_length=250, null=True),
        ),
    ]
