# Generated by Django 4.2.20 on 2025-07-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0009_alter_commontransactionsmodel_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonspacesmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='commonspacesmodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='commonspacesmodel',
            name='contact_phone',
        ),
    ]
