# Generated by Django 4.2.20 on 2025-05-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0009_commonapprovalpolicymodel_commonwarehousesmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonexpensesmodel',
            name='equity_account',
        ),
        migrations.RemoveField(
            model_name='commonexpensesmodel',
            name='funding_account',
        ),
    ]
