# Generated by Django 4.2.20 on 2025-07-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0009_alter_commonapproversmodel_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='tax_assumptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='tax_constraints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='tax_exclusions',
            field=models.TextField(blank=True, help_text='Specific items, features, or activities that are explicitly excluded from this scope.', null=True),
        ),
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='tax_resources',
            field=models.TextField(blank=True, help_text='Resources required by this particular scope', null=True),
        ),
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='tax_risks',
            field=models.TextField(blank=True, help_text='A summary of identified risks associated with this scope.', null=True),
        ),
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='tax_stakeholders',
            field=models.TextField(blank=True, help_text='Key individuals or groups affected by or having an interest in this scope.', null=True),
        ),
    ]
