# Generated by Django 4.2.20 on 2025-06-09 08:54

import allifmaalcommonapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0009_commonoperationyeartermsmodel_operation_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonoperationyeartermsmodel',
            name='ahmed',
        ),
        migrations.AlterField(
            model_name='commonoperationyeartermsmodel',
            name='operation_year',
            field=models.ForeignKey(blank=True, default=allifmaalcommonapp.models.get_default_operation_year, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termsyear', to='allifmaalcommonapp.commonoperationyearsmodel'),
        ),
    ]
