# Generated by Django 4.2.20 on 2025-09-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0010_commonspacesmodel_occupancy_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='number_of_units',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='occupancy_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Occupancy rate as a percentage', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='taken_units',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
