# Generated by Django 4.2.20 on 2025-05-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0010_remove_commonexpensesmodel_equity_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonexpensesmodel',
            name='quantity',
        ),
    ]
