# Generated by Django 4.2.20 on 2025-03-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0010_alter_commondepartmentsmodel_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='commondepartmentsmodel',
            name='updatedon',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
