# Generated by Django 4.2.20 on 2025-06-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0010_remove_commonspaceunitsmodel_area_sqft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonspaceunitsmodel',
            name='rental_price',
        ),
    ]
