# Generated by Django 4.2.20 on 2025-06-09 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0010_remove_commonoperationyeartermsmodel_ahmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonprogramsmodel',
            name='operation_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_operation_year', to='allifmaalcommonapp.commonoperationyearsmodel'),
        ),
    ]
