# Generated by Django 4.2.20 on 2025-06-09 08:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0011_commonprogramsmodel_operation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonprogramsmodel',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='commonprogramsmodel',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AddField(
            model_name='commonprogramsmodel',
            name='is_current',
            field=models.CharField(blank=True, choices=[('Current', 'Current'), ('Passed', 'Passed'), ('Future', 'Future')], default='Current', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commonprogramsmodel',
            name='operation_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms_program', to='allifmaalcommonapp.commonoperationyeartermsmodel'),
        ),
        migrations.AddField(
            model_name='commonprogramsmodel',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
