# Generated by Django 4.2.20 on 2025-06-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0011_remove_commonspaceunitsmodel_rental_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonspaceunitsmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonspaceunitsmodel',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('Room', 'Room'), ('Shop', 'Shop'), ('Office', 'Office'), ('House', 'House'), ('Warehouse', 'Warehouse'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
