# Generated by Django 4.2.20 on 2025-05-26 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0011_remove_commonexpensesmodel_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commonapproversmodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='commoncreditnoteitemsmodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='commoncreditnoteitemsmodel',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='commoncreditnotesmodel',
            name='credit_note_date',
        ),
        migrations.AddField(
            model_name='commonapproversmodel',
            name='approvers',
            field=models.ManyToManyField(related_name='apprvrusrmbmrs', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
        migrations.AddField(
            model_name='commonapproversmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apprvrbrnch', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonapproversmodel',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commonapproversmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apprvrdpt', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonapproversmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apprvrdvs', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commoncreditnotesmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchcrdtnte', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commoncreditnotesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptcrdtnte', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commoncreditnotesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvscrdtnte', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonstocktransferorderitemsmodel',
            name='comments',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='commonapproversmodel',
            name='members',
        ),
        migrations.RemoveField(
            model_name='commonapproversmodel',
            name='name',
        ),
    ]
