# Generated by Django 4.2.20 on 2025-07-28 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0011_alter_commonapproversmodel_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncustomerpaymentsmodel',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payment_coa', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
    ]
