# Generated by Django 4.2.20 on 2025-04-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0011_commondepartmentsmodel_updatedon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonledgerentriesmodel',
            old_name='origintalamount',
            new_name='originalamount',
        ),
    ]
