# Generated by Django 4.2.20 on 2025-06-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0012_commonspaceunitsmodel_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonstocksmodel',
            name='code',
        ),
        migrations.RemoveField(
            model_name='commonstocksmodel',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='commonstocksmodel',
            name='drugDescription',
        ),
        migrations.RemoveField(
            model_name='commonstocksmodel',
            name='drugUnit',
        ),
        migrations.RemoveField(
            model_name='commonstocksmodel',
            name='drug_notes',
        ),
        migrations.RemoveField(
            model_name='commonstocksmodel',
            name='drugform',
        ),
        migrations.RemoveField(
            model_name='commonstocksmodel',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='commonstocksmodel',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='commonstocksmodel',
            name='item_is_physical_or_service',
        ),
        migrations.RemoveField(
            model_name='commonstocksmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='commonstocksmodel',
            name='normal_range_info',
        ),
        migrations.RemoveField(
            model_name='commonstocksmodel',
            name='operation_term',
        ),
        migrations.RemoveField(
            model_name='commonstocksmodel',
            name='operation_year',
        ),
        migrations.RemoveField(
            model_name='commonstocksmodel',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='commonstocksmodel',
            name='unit_of_measure',
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='height',
            field=models.CharField(blank=True, default='notes', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='item_state',
            field=models.CharField(blank=True, choices=[('Physical', 'Physical'), ('Service', 'Service')], default='Current', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='length',
            field=models.CharField(blank=True, default='notes', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='normal_range',
            field=models.CharField(blank=True, help_text="General normal range information for this test (e.g., '70-110 mg/dL').", max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_of_measure_stocks', to='allifmaalcommonapp.commonunitsmodel'),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='weight',
            field=models.CharField(blank=True, default='notes', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='width',
            field=models.CharField(blank=True, default='notes', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
