# Generated by Django 4.2.20 on 2025-07-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0012_commoncustomerpaymentsmodel_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='commontransitmodel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transit_currency', to='allifmaalcommonapp.commoncurrenciesmodel'),
        ),
        migrations.AddField(
            model_name='commontransitmodel',
            name='terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transit_payment_terms', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
    ]
