# Generated by Django 4.2.20 on 2025-06-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0012_commonprogramsmodel_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonprogramsmodel',
            name='ahmed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
