# Generated by Django 4.2.20 on 2025-05-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0012_alter_commonapproversmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commoncreditnotesmodel',
            old_name='credit_note_number',
            new_name='number',
        ),
    ]
