# Generated by Django 4.2.20 on 2025-04-25 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0012_rename_origintalamount_commonledgerentriesmodel_originalamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonjobitemsmodel',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='commonjobitemsmodel',
            name='description',
        ),
        migrations.AlterField(
            model_name='commonbranchesmodel',
            name='branchslug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commoncompanydetailsmodel',
            name='companyslug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commondatasortsmodel',
            name='name',
            field=models.CharField(default='asc', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='commondepartmentsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dpmntbrnch', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AlterField(
            model_name='commondepartmentsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cmpdprmnt', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commondepartmentsmodel',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commondepartmentsmodel',
            name='departmentslug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commondepartmentsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dpmntdvsn', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AlterField(
            model_name='commondivisionsmodel',
            name='divisionslug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commondocsformatmodel',
            name='name',
            field=models.CharField(default='pdf', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='commontaxparametersmodel',
            name='taxdescription',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
