# Generated by Django 4.2.20 on 2025-06-09 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0013_commonprogramsmodel_ahmed'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='commonprogramsmodel',
            name='muse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commonprioritylevelsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvs_priroties_levels', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AlterField(
            model_name='commonprogramsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_programm', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AlterField(
            model_name='commonprogramsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownr_programm', to=settings.AUTH_USER_MODEL),
        ),
    ]
