# Generated by Django 4.2.20 on 2025-04-25 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0013_remove_commonjobitemsmodel_comments_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateLink',
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='terms',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='commoncustomerpaymentsmodel',
            name='mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card')], default='Cash', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='commoncustomersmodel',
            name='paymentType',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card')], default='Cash', max_length=30),
        ),
        migrations.AlterField(
            model_name='commonemployeesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emplcomprlnmefsammnapp', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commonemployeesmodel',
            name='staffNo',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='commonemployeesmodel',
            name='stffslug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonemployeesmodel',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='commonexpensesmodel',
            name='comments',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonexpensesmodel',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonexpensesmodel',
            name='mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card')], default='Cash', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='invoice_terms',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Deposit', 'Deposit'), ('15 days', '15 days'), ('30 days', '30 days'), ('Other', 'Other')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='terms',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Deposit', 'Deposit'), ('15 days', '15 days'), ('30 days', '30 days'), ('Other', 'Other')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='commonpurchaseordersmodel',
            name='payment_terms',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='commonsalariesmodel',
            name='mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card')], default='Cash', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='commonstockcategoriesmodel',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='description',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='partNumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='commonsuppliersmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppusrlnm', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commonsuppliersmodel',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commontaxparametersmodel',
            name='taxdescription',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
