# Generated by Django 4.2.20 on 2025-06-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0013_remove_commonstocksmodel_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncodesmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='height',
            field=models.CharField(blank=True, default='height', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='length',
            field=models.CharField(blank=True, default='length', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='weight',
            field=models.CharField(blank=True, default='weight', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='width',
            field=models.CharField(blank=True, default='width', max_length=250, null=True),
        ),
    ]
