# Generated by Django 4.2.20 on 2025-05-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0013_rename_credit_note_number_commoncreditnotesmodel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonstocksmodel',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stckwarehouse', to='allifmaalcommonapp.commonwarehousesmodel'),
        ),
    ]
