# Generated by Django 4.2.20 on 2025-05-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0014_commonstocksmodel_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonstocktransferordersmodel',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('posted', 'posted')], default='waiting', max_length=20),
        ),
    ]
