# Generated by Django 4.2.20 on 2025-06-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0014_remove_commonprogramsmodel_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonprogramsmodel',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
