# Generated by Django 4.2.20 on 2025-04-25 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0014_delete_templatelink_alter_commonassetsmodel_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='txpbrcnh', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='txprdptm', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dvstxprm', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
    ]
