# Generated by Django 4.2.20 on 2025-06-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0014_commoncodesmodel_date_alter_commonstocksmodel_height_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commondivisionsmodel',
            unique_together={('company', 'division')},
        ),
    ]
