# Generated by Django 4.2.20 on 2025-06-20 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0015_alter_commondivisionsmodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commonbranchesmodel',
            unique_together={('branch', 'division', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='commondepartmentsmodel',
            unique_together={('company', 'division', 'branch')},
        ),
    ]
