# Generated by Django 4.2.20 on 2025-06-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0015_commonprogramsmodel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonprogramsmodel',
            name='ahmed',
        ),
        migrations.RemoveField(
            model_name='commonprogramsmodel',
            name='muse',
        ),
        migrations.AlterField(
            model_name='commonprogramsmodel',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Active'),
        ),
    ]
