# Generated by Django 4.2.20 on 2025-05-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0016_commondivisionsmodel_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commondivisionsmodel',
            options={},
        ),
        migrations.AlterField(
            model_name='commondivisionsmodel',
            name='division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
