# Generated by Django 4.2.20 on 2025-06-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0016_alter_commonbranchesmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commoncodesmodel',
            unique_together={('company', 'code', 'name')},
        ),
    ]
