# Generated by Django 4.2.20 on 2025-06-09 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0016_remove_commonprogramsmodel_ahmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonservicesmodel',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='commonservicesmodel',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AddField(
            model_name='commonservicesmodel',
            name='is_current',
            field=models.CharField(blank=True, choices=[('Current', 'Current'), ('Passed', 'Passed'), ('Future', 'Future')], default='Current', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commonservicesmodel',
            name='operation_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_program', to='allifmaalcommonapp.commonoperationyeartermsmodel'),
        ),
        migrations.AddField(
            model_name='commonservicesmodel',
            name='operation_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_operation_year', to='allifmaalcommonapp.commonoperationyearsmodel'),
        ),
        migrations.AddField(
            model_name='commonservicesmodel',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AlterField(
            model_name='commonservicesmodel',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Active'),
        ),
    ]
