# Generated by Django 4.2.20 on 2025-05-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0016_alter_commonstocktransferorderitemsmodel_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonpurchaseordersmodel',
            name='approval_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Issued', 'Issued (GIN Created)'), ('Received', 'Received (GRN Created)'), ('Cancelled', 'Cancelled')], default='Draft', max_length=50),
        ),
    ]
