# Generated by Django 4.2.20 on 2025-05-01 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0017_alter_commondivisionsmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commondivisionsmodel',
            name='delete',
        ),
    ]
