# Generated by Django 4.2.20 on 2025-06-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0017_commonservicesmodel_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonprogramsmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
