# Generated by Django 4.2.20 on 2025-06-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0017_alter_commoncodesmodel_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='blood_pressure_diastolic',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='blood_pressure_systolic',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='chief_complaints',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='complaints',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='current_medications_at_triage',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='encounter_type',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='end_date_time',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='height',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='known_chronic_conditions_triage',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='main_complaints',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='order_date_time',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='oxygen_saturation',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='past_medical_history',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='pulse_rate',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='respiration_rate',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='treatment_plan',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='triage_date_time',
        ),
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='weight',
        ),
        migrations.AddField(
            model_name='commontransactionsmodel',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms_payment_mode_trans', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
        migrations.AlterField(
            model_name='commontransactionsmodel',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='The customer associated with this encounter.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custmtransrlnme', to='allifmaalcommonapp.commoncustomersmodel'),
        ),
        migrations.AlterField(
            model_name='commontransactionsmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='commontransactionsmodel',
            name='employee_in_charge',
            field=models.ForeignKey(blank=True, help_text='The main employee attending this encounter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters_as_primary_doctor', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
    ]
