# Generated by Django 4.2.20 on 2025-05-28 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0017_commonpurchaseordersmodel_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonwarehousesmodel',
            name='inventory_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invaccwrhse', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
    ]
