# Generated by Django 4.2.20 on 2025-06-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0018_commonprogramsmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonprogramsmodel',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
