# Generated by Django 4.2.20 on 2025-05-03 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0018_remove_commondivisionsmodel_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoncompanydetailsmodel',
            name='branch',
        ),
    ]
