# Generated by Django 4.2.20 on 2025-06-20 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0018_remove_commontransactionsmodel_blood_pressure_diastolic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonspacebookingitemsmodel',
            name='space_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_space_unit', to='allifmaalcommonapp.commonspaceunitsmodel'),
        ),
    ]
