# Generated by Django 4.2.20 on 2025-05-28 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0018_commonwarehousesmodel_inventory_account'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commonstocksmodel',
            unique_together={('company', 'partNumber', 'warehouse')},
        ),
    ]
