# Generated by Django 4.2.20 on 2025-06-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0019_commonspacebookingitemsmodel_space_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonspacebookingitemsmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
