# Generated by Django 4.2.20 on 2025-05-29 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0019_alter_commonstocksmodel_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonWarehouseItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=30, null=True)),
                ('comments', models.CharField(blank=True, max_length=30, null=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrhseitemsstck', to='allifmaalcommonapp.commonstocksmodel')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrhseitms', to='allifmaalcommonapp.commonwarehousesmodel')),
            ],
        ),
    ]
