# Generated by Django 4.2.20 on 2025-05-03 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0019_remove_commoncompanydetailsmodel_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonbranchesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dvnscmpny', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AlterField(
            model_name='commoncompanydetailsmodel',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secrlmown', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commondivisionsmodel',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dvsncmpny', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commondivisionsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owncmpndvsn', to=settings.AUTH_USER_MODEL),
        ),
    ]
