# Generated by Django 4.2.20 on 2025-06-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0019_alter_commonprogramsmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonprogramsmodel',
            name='is_active',
        ),
    ]
