# Generated by Django 4.2.20 on 2025-06-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0020_remove_commonprogramsmodel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonprogramsmodel',
            name='comments',
        ),
    ]
