# Generated by Django 4.2.20 on 2025-06-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0020_commonspacebookingitemsmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commontransactionsmodel',
            name='date',
        ),
    ]
