# Generated by Django 4.2.20 on 2025-05-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0020_commonwarehouseitemsmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commonwarehouseitemsmodel',
            unique_together={('items', 'warehouse')},
        ),
        migrations.RemoveField(
            model_name='commonwarehouseitemsmodel',
            name='comments',
        ),
    ]
