# Generated by Django 4.2.20 on 2025-06-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0021_remove_commonprogramsmodel_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonservicesmodel',
            old_name='service_name',
            new_name='name',
        ),
    ]
