# Generated by Django 4.2.20 on 2025-06-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0021_remove_commontransactionsmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commontransactionsmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
