# Generated by Django 4.2.20 on 2025-06-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0022_commontransactionsmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonspacebookingitemsmodel',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, null=True),
        ),
    ]
