# Generated by Django 4.2.20 on 2025-06-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0022_rename_service_name_commonservicesmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonservicesmodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='commonservicesmodel',
            name='lastUpdated',
        ),
        migrations.RemoveField(
            model_name='commonservicesmodel',
            name='service_description',
        ),
        migrations.AlterField(
            model_name='commonservicesmodel',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
