# Generated by Django 4.2.20 on 2025-05-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0022_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncompanydetailsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Blocked', 'Block Entity'), ('Unblock', 'Unblock Entity')], default='Blocked', max_length=30, null=True),
        ),
    ]
