# Generated by Django 4.2.20 on 2025-05-30 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0022_alter_commonstocktransferorderitemsmodel_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonstocktransferorderitemsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmpnintcmrtrasnf', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
    ]
