# Generated by Django 4.2.20 on 2025-05-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0023_commoncompanydetailsmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncompanydetailsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Blocked', 'Entity Blocked'), ('Unblocked', 'Entity Unblocked')], default='Blocked', max_length=30, null=True),
        ),
    ]
