# Generated by Django 4.2.20 on 2025-06-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0023_remove_commonservicesmodel_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonservicesmodel',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_of_measure_services', to='allifmaalcommonapp.commonunitsmodel'),
        ),
    ]
