# Generated by Django 4.2.20 on 2025-06-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0023_commonspacebookingitemsmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='commontransactionsmodel',
            name='total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
    ]
