# Generated by Django 4.2.20 on 2025-06-09 17:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0024_alter_commonservicesmodel_unit_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonstockcategoriesmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commonstockcategoriesmodel',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AddField(
            model_name='commonstockcategoriesmodel',
            name='is_current',
            field=models.CharField(blank=True, choices=[('Current', 'Current'), ('Passed', 'Passed'), ('Future', 'Future')], default='Current', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commonstockcategoriesmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commonstockcategoriesmodel',
            name='operation_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms_categories', to='allifmaalcommonapp.commonoperationyeartermsmodel'),
        ),
        migrations.AddField(
            model_name='commonstockcategoriesmodel',
            name='operation_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories_operation_year', to='allifmaalcommonapp.commonoperationyearsmodel'),
        ),
        migrations.AddField(
            model_name='commonstockcategoriesmodel',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Course code, e.g., CS101', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='credits',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Credit hours for the course', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='is_current',
            field=models.CharField(blank=True, choices=[('Current', 'Current'), ('Passed', 'Passed'), ('Future', 'Future')], default='Current', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='normal_range_info',
            field=models.CharField(blank=True, help_text="General normal range information for this test (e.g., '70-110 mg/dL').", max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='operation_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks_program', to='allifmaalcommonapp.commonoperationyeartermsmodel'),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='operation_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks_operation_year', to='allifmaalcommonapp.commonoperationyearsmodel'),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AddField(
            model_name='commonstocksmodel',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_of_measure_stocks', to='allifmaalcommonapp.commonunitsmodel'),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
