# Generated by Django 4.2.20 on 2025-06-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0024_commontransactionsmodel_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commontransactionsmodel',
            old_name='total',
            new_name='amount',
        ),
    ]
