# Generated by Django 4.2.20 on 2025-05-30 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0024_remove_commonstocktransferorderitemsmodel_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonstocktransferorderitemsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmpnintcmpsfgfdtcktrnsfrs', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
    ]
