# Generated by Django 4.2.20 on 2025-06-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0025_rename_total_commontransactionsmodel_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonprogressmodel',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='commonprogressmodel',
            name='recording_date_time',
        ),
        migrations.AddField(
            model_name='commonprogressmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
