# Generated by Django 4.2.20 on 2025-05-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0025_commonstocktransferorderitemsmodel_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonstocktransferorderitemsmodel',
            name='company',
        ),
    ]
