# Generated by Django 4.2.20 on 2025-06-09 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0025_commonstockcategoriesmodel_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonattendancesmodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='commoncustomersmodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='commonfeesmodel',
            name='program',
        ),
        migrations.AddField(
            model_name='commonattendancesmodel',
            name='course_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_attendances', to='allifmaalcommonapp.commonstockcategoriesmodel'),
        ),
        migrations.AddField(
            model_name='commoncustomersmodel',
            name='course_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='allifmaalcommonapp.commonstockcategoriesmodel'),
        ),
        migrations.AddField(
            model_name='commonfeesmodel',
            name='program_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs_fee_structures', to='allifmaalcommonapp.commonstockcategoriesmodel'),
        ),
        migrations.AlterField(
            model_name='commonassessmentsmodel',
            name='charged_service',
            field=models.ForeignKey(blank=True, help_text='The specific medical service entry used for billing this lab test.', limit_choices_to={'service_type': 'LAB'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labortry_order_charges', to='allifmaalcommonapp.commonstockcategoriesmodel'),
        ),
        migrations.AlterField(
            model_name='commonassessmentsmodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_assessments', to='allifmaalcommonapp.commonstockcategoriesmodel'),
        ),
        migrations.AlterField(
            model_name='commonassessmentsmodel',
            name='test_for',
            field=models.ForeignKey(blank=True, help_text='The type of lab test ordered.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_orders', to='allifmaalcommonapp.commonstockcategoriesmodel'),
        ),
        migrations.AlterField(
            model_name='commonassessmentsmodel',
            name='test_from',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lbtsfrm', to='allifmaalcommonapp.commonstockcategoriesmodel'),
        ),
        migrations.AlterField(
            model_name='commonresultsmodel',
            name='charged_service',
            field=models.ForeignKey(blank=True, help_text='The specific medical service entry used for billing this lab test.', limit_choices_to={'service_type': 'LAB'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_order_charges', to='allifmaalcommonapp.commonstockcategoriesmodel'),
        ),
        migrations.AlterField(
            model_name='commonresultsmodel',
            name='test_from',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lbtestreln', to='allifmaalcommonapp.commonstockcategoriesmodel'),
        ),
    ]
