# Generated by Django 4.2.20 on 2025-05-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0025_alter_commoncompanydetailsmodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='terms',
            field=models.CharField(choices=[('Cash pay', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='commoncustomerpaymentsmodel',
            name='mode',
            field=models.CharField(blank=True, choices=[('Cash pay', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card')], default='Cash', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='commoncustomersmodel',
            name='paymentType',
            field=models.CharField(choices=[('Cash pay', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card')], default='Cash', max_length=30),
        ),
        migrations.AlterField(
            model_name='commonexpensesmodel',
            name='mode',
            field=models.CharField(choices=[('Cash pay', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card')], default='Cash', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseordersmodel',
            name='payment_terms',
            field=models.CharField(choices=[('Cash pay', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='commonsalariesmodel',
            name='mode',
            field=models.CharField(blank=True, choices=[('Cash pay', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card')], default='Cash', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='commonsupplierpaymentsmodel',
            name='mode',
            field=models.CharField(blank=True, choices=[('Cash pay', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card')], default='Cash', max_length=20, null=True),
        ),
    ]
