# Generated by Django 4.2.20 on 2025-06-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0026_remove_commonattendancesmodel_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonstocksmodel',
            name='item_is_physical_or_service',
            field=models.CharField(blank=True, choices=[('Physical', 'Physical'), ('Service', 'Service')], default='Current', max_length=50, null=True),
        ),
    ]
