# Generated by Django 4.2.20 on 2025-06-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0026_remove_commonprogressmodel_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonprogressmodel',
            name='recorded_by',
        ),
    ]
