# Generated by Django 4.2.20 on 2025-05-30 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0026_remove_commonstocktransferorderitemsmodel_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonstocktransferorderitemsmodel',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stcktrnsfordrlns', to='allifmaalcommonapp.commonstocksmodel'),
        ),
    ]
