# Generated by Django 4.2.20 on 2025-05-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0026_alter_commonassetsmodel_terms_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='terms',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Deposit', 'Deposit'), ('Credit', 'Credit'), ('Transfer', 'Transfer'), ('Cheque', 'Cheque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='commoncustomerpaymentsmodel',
            name='mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Deposit', 'Deposit'), ('Credit', 'Credit'), ('Transfer', 'Transfer'), ('Cheque', 'Cheque')], default='Cash', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='commoncustomersmodel',
            name='paymentType',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Deposit', 'Deposit'), ('Credit', 'Credit'), ('Transfer', 'Transfer'), ('Cheque', 'Cheque')], default='Cash', max_length=30),
        ),
        migrations.AlterField(
            model_name='commonexpensesmodel',
            name='mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Deposit', 'Deposit'), ('Credit', 'Credit'), ('Transfer', 'Transfer'), ('Cheque', 'Cheque')], default='Cash', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseorderitemsmodel',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseorderitemsmodel',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseorderitemsmodel',
            name='taxRate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseorderitemsmodel',
            name='unitcost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseordersmodel',
            name='amounttaxincl',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseordersmodel',
            name='grandtotal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseordersmodel',
            name='misccosts',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseordersmodel',
            name='payment_terms',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Deposit', 'Deposit'), ('Credit', 'Credit'), ('Transfer', 'Transfer'), ('Cheque', 'Cheque')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='commonsalariesmodel',
            name='mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Deposit', 'Deposit'), ('Credit', 'Credit'), ('Transfer', 'Transfer'), ('Cheque', 'Cheque')], default='Cash', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='commonsupplierpaymentsmodel',
            name='mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Deposit', 'Deposit'), ('Credit', 'Credit'), ('Transfer', 'Transfer'), ('Cheque', 'Cheque')], default='Cash', max_length=20, null=True),
        ),
    ]
