# Generated by Django 4.2.20 on 2025-06-21 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0027_remove_commonprogressmodel_recorded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commontransactionsmodel',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='The customer associated with this encounter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custmtransrlnme', to='allifmaalcommonapp.commoncustomersmodel'),
        ),
    ]
