# Generated by Django 4.2.20 on 2025-06-09 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0027_commonstocksmodel_item_is_physical_or_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonstockcategoriesmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonstockcategoriesmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonstockcategoriesmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonstockcategoriesmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonstockcategoriesmodel',
            name='operation_term',
        ),
        migrations.RemoveField(
            model_name='commonstockcategoriesmodel',
            name='operation_year',
        ),
        migrations.RemoveField(
            model_name='commonstockcategoriesmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commoncategoriesmodel',
            name='is_active',
        ),
        migrations.AddField(
            model_name='commoncategoriesmodel',
            name='comments',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commoncategoriesmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='commoncategoriesmodel',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AddField(
            model_name='commoncategoriesmodel',
            name='is_current',
            field=models.CharField(blank=True, choices=[('Current', 'Current'), ('Passed', 'Passed'), ('Future', 'Future')], default='Current', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commoncategoriesmodel',
            name='operation_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms_categories', to='allifmaalcommonapp.commonoperationyeartermsmodel'),
        ),
        migrations.AddField(
            model_name='commoncategoriesmodel',
            name='operation_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories_operation_year', to='allifmaalcommonapp.commonoperationyearsmodel'),
        ),
        migrations.AddField(
            model_name='commoncategoriesmodel',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AlterField(
            model_name='commonassessmentsmodel',
            name='charged_service',
            field=models.ForeignKey(blank=True, help_text='The specific medical service entry used for billing this lab test.', limit_choices_to={'service_type': 'LAB'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labortry_order_charges', to='allifmaalcommonapp.commoncategoriesmodel'),
        ),
        migrations.AlterField(
            model_name='commonassessmentsmodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_assessments', to='allifmaalcommonapp.commoncategoriesmodel'),
        ),
        migrations.AlterField(
            model_name='commonassessmentsmodel',
            name='test_for',
            field=models.ForeignKey(blank=True, help_text='The type of lab test ordered.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_orders', to='allifmaalcommonapp.commoncategoriesmodel'),
        ),
        migrations.AlterField(
            model_name='commonassessmentsmodel',
            name='test_from',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lbtsfrm', to='allifmaalcommonapp.commoncategoriesmodel'),
        ),
        migrations.AlterField(
            model_name='commonattendancesmodel',
            name='course_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_attendances', to='allifmaalcommonapp.commoncategoriesmodel'),
        ),
        migrations.AlterField(
            model_name='commoncategoriesmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchstockcats', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AlterField(
            model_name='commoncategoriesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmnstcatrln', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commoncategoriesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptstockcats', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AlterField(
            model_name='commoncategoriesmodel',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncategoriesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsstockcats', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AlterField(
            model_name='commoncategoriesmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnurstkcat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commoncustomersmodel',
            name='course_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='allifmaalcommonapp.commoncategoriesmodel'),
        ),
        migrations.AlterField(
            model_name='commonfeesmodel',
            name='program_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs_fee_structures', to='allifmaalcommonapp.commoncategoriesmodel'),
        ),
        migrations.AlterField(
            model_name='commonresultsmodel',
            name='charged_service',
            field=models.ForeignKey(blank=True, help_text='The specific medical service entry used for billing this lab test.', limit_choices_to={'service_type': 'LAB'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_order_charges', to='allifmaalcommonapp.commoncategoriesmodel'),
        ),
        migrations.AlterField(
            model_name='commonresultsmodel',
            name='test_from',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lbtestreln', to='allifmaalcommonapp.commoncategoriesmodel'),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catinvtconrlnm', to='allifmaalcommonapp.commoncategoriesmodel'),
        ),
    ]
