# Generated by Django 4.2.20 on 2025-05-31 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0027_alter_commonstocktransferorderitemsmodel_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncreditnoteitemsmodel',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commoncreditnotesmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credntown', to=settings.AUTH_USER_MODEL),
        ),
    ]
