# Generated by Django 4.2.20 on 2025-05-17 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0027_delete_product_alter_commonassetsmodel_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonpurchaseorderitemsmodel',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseorderitemsmodel',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseorderitemsmodel',
            name='taxRate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseorderitemsmodel',
            name='unitcost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseordersmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseordersmodel',
            name='uplift',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='CommonCurrenciesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, null=True)),
                ('comments', models.CharField(max_length=30, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currnybrnch', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmpcrrncy', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currncydpt', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvscrrncy', to='allifmaalcommonapp.commondivisionsmodel')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owncrrncy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
