# Generated by Django 4.2.20 on 2025-06-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0006_alter_appointmentsmodel_scheduled_service'),
        ('allifmaalcommonapp', '0028_remove_commonstockcategoriesmodel_branch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonStockCategoriesModel',
        ),
    ]
