# Generated by Django 4.2.20 on 2025-05-17 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0028_alter_commonpurchaseorderitemsmodel_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonpurchaseordersmodel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crrncypo', to='allifmaalcommonapp.commoncurrenciesmodel'),
        ),
    ]
