# Generated by Django 4.2.20 on 2025-06-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0028_alter_commontransactionsmodel_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commontransitmodel',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='commontransitmodel',
            name='unit_of_measure',
        ),
        migrations.AlterField(
            model_name='commonprogressmodel',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='commontransitmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
