# Generated by Django 4.2.20 on 2025-06-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0029_remove_commontransitmodel_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commontransitmodel',
            name='entry_date',
        ),
        migrations.AddField(
            model_name='commontransitmodel',
            name='received_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
