# Generated by Django 4.2.20 on 2025-05-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0029_commonpurchaseordersmodel_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonpurchaseordersmodel',
            name='delivery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
