# Generated by Django 4.2.20 on 2025-06-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0029_delete_commonstockcategoriesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonprojecttasksmodel',
            name='priority_level',
            field=models.CharField(blank=True, choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('URGENT', 'Urgent')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='CommonPriorityLevelsModel',
        ),
    ]
