# Generated by Django 4.2.20 on 2025-05-31 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0029_alter_commoncreditnotesmodel_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoncreditnoteitemsmodel',
            name='return_location',
        ),
        migrations.AddField(
            model_name='commoncreditnotesmodel',
            name='return_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allifmaalcommonapp.commonwarehousesmodel'),
        ),
    ]
