# Generated by Django 4.2.20 on 2025-06-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0030_remove_commontransitmodel_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commontransitmodel',
            name='delivery_confirmation_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
