# Generated by Django 4.2.20 on 2025-06-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0030_alter_commonprojecttasksmodel_priority_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commondiagnosesmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commondiagnosesmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commondiagnosesmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commondiagnosesmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commondiagnosesmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonlaboratoriesmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonlaboratoriesmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonlaboratoriesmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonlaboratoriesmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonlaboratoriesmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonprogresstatusmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonprogresstatusmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonprogresstatusmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonprogresstatusmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonprogresstatusmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonassessmentsmodel',
            name='diagnoses',
        ),
        migrations.RemoveField(
            model_name='commonassessmentsmodel',
            name='lab_name',
        ),
        migrations.RemoveField(
            model_name='commonresultsmodel',
            name='lab_name',
        ),
        migrations.AlterField(
            model_name='commonprojecttasksmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('AVAIL', 'Available'), ('OCC', 'Occupied'), ('RESERVED', 'Reserved'), ('CLEAN', 'Needs Cleaning')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='CommonAttendancesModel',
        ),
        migrations.DeleteModel(
            name='CommonDiagnosesModel',
        ),
        migrations.DeleteModel(
            name='CommonLaboratoriesModel',
        ),
        migrations.DeleteModel(
            name='CommonProgresStatusModel',
        ),
    ]
