# Generated by Django 4.2.20 on 2025-05-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0030_remove_commoncreditnoteitemsmodel_return_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncreditnotesmodel',
            name='status',
            field=models.CharField(blank=True, default='Draft', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commoncreditnotesmodel',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
    ]
