# Generated by Django 4.2.20 on 2025-05-31 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0031_alter_commoncreditnotesmodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncreditnoteitemsmodel',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crdntitems', to='allifmaalcommonapp.commoncreditnotesmodel'),
        ),
    ]
