# Generated by Django 4.2.20 on 2025-05-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0031_commonpaymenttermsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonpurchaseordersmodel',
            name='payment_terms',
        ),
    ]
