# Generated by Django 4.2.20 on 2025-06-09 20:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0031_remove_commondiagnosesmodel_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonordersmodel',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commonordersmodel',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commonordersmodel',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commonordersmodel',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AddField(
            model_name='commonordersmodel',
            name='is_current',
            field=models.CharField(blank=True, choices=[('Current', 'Current'), ('Passed', 'Passed'), ('Future', 'Future')], default='Current', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commonordersmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commonordersmodel',
            name='operation_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms_common_orders', to='allifmaalcommonapp.commonoperationyeartermsmodel'),
        ),
        migrations.AddField(
            model_name='commonordersmodel',
            name='operation_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_orders_operation_year', to='allifmaalcommonapp.commonoperationyearsmodel'),
        ),
        migrations.AddField(
            model_name='commonordersmodel',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.DeleteModel(
            name='CommonFeesModel',
        ),
    ]
