# Generated by Django 4.2.20 on 2025-06-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0031_alter_commontransitmodel_delivery_confirmation_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commontransitmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
