# Generated by Django 4.2.20 on 2025-05-18 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0032_remove_commonpurchaseordersmodel_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonpurchaseordersmodel',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='popymnterms', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
    ]
