# Generated by Django 4.2.20 on 2025-06-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0032_alter_commontransitmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commontransitmodel',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_received_by_emplye', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
    ]
