# Generated by Django 4.2.20 on 2025-05-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0032_alter_commoncreditnoteitemsmodel_credit_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncreditnoteitemsmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
