# Generated by Django 4.2.20 on 2025-06-10 04:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalshaafiapp', '0006_alter_appointmentsmodel_scheduled_service'),
        ('allifmaalcommonapp', '0032_commonordersmodel_code_commonordersmodel_comments_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommonOrdersModel',
            new_name='CommonTransactionEventsModel',
        ),
    ]
