# Generated by Django 4.2.20 on 2025-06-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0033_alter_commontransitmodel_received_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commontransititemsmodel',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_units_shipment', to='allifmaalcommonapp.commonunitsmodel'),
        ),
    ]
