# Generated by Django 4.2.20 on 2025-05-31 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0033_commoncreditnoteitemsmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonapproversmodel',
            name='approvers',
        ),
        migrations.AddField(
            model_name='commonapproversmodel',
            name='approvers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apprvrusrmbmrs', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
    ]
