# Generated by Django 4.2.20 on 2025-05-18 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0033_commonpurchaseordersmodel_payment_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonquotesmodel',
            name='terms',
        ),
        migrations.AddField(
            model_name='commonquotesmodel',
            name='delivery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commonquotesmodel',
            name='descriptioncc',
            field=models.CharField(blank=True, default='Quotation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commonquotesmodel',
            name='descriptionccdfd',
            field=models.CharField(blank=True, default='Quotation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commonquotesmodel',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qtesspymnterm', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
    ]
