# Generated by Django 4.2.20 on 2025-06-10 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0033_rename_commonordersmodel_commontransactioneventsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commontransactioneventsmodel',
            old_name='order_number',
            new_name='trans_number',
        ),
    ]
