# Generated by Django 4.2.20 on 2025-05-18 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0034_remove_commonquotesmodel_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonquotesmodel',
            name='descriptioncc',
            field=models.CharField(blank=True, default='Quotationssdf', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commonquotesmodel',
            name='descriptionccdfd',
            field=models.CharField(blank=True, default='Quotationdf', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commonquotesmodel',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qtesspymntermdd', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
    ]
