# Generated by Django 4.2.20 on 2025-05-31 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0034_remove_commonapproversmodel_approvers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonapprovalrequestsmodel',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='commonapprovalrequestsmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonapprovalrequestsmodel',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='commonapprovalrequestsmodel',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='commonapprovalrequestsmodel',
            name='initiated_by',
        ),
        migrations.RemoveField(
            model_name='commonapprovalrequestsmodel',
            name='policy',
        ),
        migrations.AlterUniqueTogether(
            name='commonapprovalstepsmodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='commonapprovalstepsmodel',
            name='approver_group',
        ),
        migrations.RemoveField(
            model_name='commonapprovalstepsmodel',
            name='policy',
        ),
        migrations.DeleteModel(
            name='CommonApprovalLogsModel',
        ),
        migrations.DeleteModel(
            name='CommonApprovalRequestsModel',
        ),
        migrations.DeleteModel(
            name='CommonApprovalStepsModel',
        ),
    ]
