# Generated by Django 4.2.20 on 2025-06-10 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0034_rename_order_number_commontransactioneventsmodel_trans_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commontransactioneventsmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commontransactioneventsmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commontransactioneventsmodel',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='commontransactioneventsmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commontransactioneventsmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commontransactioneventsmodel',
            name='employee_in_charge',
        ),
        migrations.RemoveField(
            model_name='commontransactioneventsmodel',
            name='operation_term',
        ),
        migrations.RemoveField(
            model_name='commontransactioneventsmodel',
            name='operation_year',
        ),
        migrations.RemoveField(
            model_name='commontransactioneventsmodel',
            name='owner',
        ),
        migrations.CreateModel(
            name='CommonTransactionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_number', models.CharField(blank=True, max_length=50, null=True)),
                ('order_date_time', models.DateTimeField(auto_now_add=True, help_text='Date and time when this patient encounter record was created.', null=True)),
                ('main_complaints', models.TextField(blank=True, help_text="The main reason for the patient's visit.", null=True)),
                ('encounter_type', models.CharField(blank=True, choices=[('OUTP', 'Outpatient Visit'), ('INPAT', 'Inpatient Admission'), ('EMER', 'Emergency Visit'), ('TELE', 'Teleconsultation'), ('FOLLOW', 'Follow-up Visit')], default='OUTP', help_text='Type of medical encounter (e.g., Outpatient, Inpatient, Emergency).', max_length=100, null=True)),
                ('end_date_time', models.DateTimeField(blank=True, help_text='Date and time when the encounter officially ended.', null=True)),
                ('status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Pending', 'Pending')], default='Open', help_text='Current status of the encounter.', max_length=20, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('diagnosis', models.TextField(blank=True, default='diagnosis', max_length=250, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('start_date', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('end_date', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('is_current', models.CharField(blank=True, choices=[('Current', 'Current'), ('Passed', 'Passed'), ('Future', 'Future')], default='Current', max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_encounters', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_encounters', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('customer', models.ForeignKey(blank=True, help_text='The patient associated with this encounter.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicalrecordcustmr', to='allifmaalcommonapp.commoncustomersmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_encounters', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_encounters', to='allifmaalcommonapp.commondivisionsmodel')),
                ('employee_in_charge', models.ForeignKey(blank=True, help_text='The main doctor attending this encounter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters_as_primary_doctor', to='allifmaalcommonapp.commonemployeesmodel')),
                ('operation_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms_common_orders', to='allifmaalcommonapp.commonoperationyeartermsmodel')),
                ('operation_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_orders_operation_year', to='allifmaalcommonapp.commonoperationyearsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_encounters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='commonassessmentsmodel',
            name='order',
            field=models.ForeignKey(blank=True, help_text='The encounter this triage record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mdclrcdobsv', to='allifmaalcommonapp.commontransactionsmodel'),
        ),
        migrations.AlterField(
            model_name='commonresultsmodel',
            name='result_for_order',
            field=models.ForeignKey(blank=True, help_text='The encounter this lab order belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='allifmaalcommonapp.commontransactionsmodel'),
        ),
        migrations.AlterField(
            model_name='commontrackingmodel',
            name='tracked_order',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labsmpletracking', to='allifmaalcommonapp.commontransactionsmodel'),
        ),
    ]
