# Generated by Django 4.2.20 on 2025-06-21 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0034_alter_commontransititemsmodel_unit_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='comments',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consigneerelated', to='allifmaalcommonapp.commoncustomersmodel'),
        ),
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='consigner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignerrelated', to='allifmaalcommonapp.commoncustomersmodel'),
        ),
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='destination',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='details',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='height',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='lenth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payerrelated', to='allifmaalcommonapp.commoncustomersmodel'),
        ),
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='rate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Booked', 'Booked'), ('Loaded', 'Loaded'), ('Dispatched', 'Dispatched'), ('Enroute', 'Enroute'), ('Delivered', 'Delivered'), ('Unknown', 'Unknown'), ('Other', 'Other')], default='Booked', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='width',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
