# Generated by Django 4.2.20 on 2025-06-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0035_remove_commontransactioneventsmodel_branch_and_more'),
        ('allifmaalshaafiapp', '0007_alter_admissionsmodel_medical_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonTransactionEventsModel',
        ),
    ]
