# Generated by Django 4.2.20 on 2025-05-18 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0035_alter_commonquotesmodel_descriptioncc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonquotesmodel',
            name='descriptionccdf',
            field=models.CharField(blank=True, default='Quotationssdfdfsf', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commonquotesmodel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crrncyqtess', to='allifmaalcommonapp.commoncurrenciesmodel'),
        ),
        migrations.AlterField(
            model_name='commonquotesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptqtess', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
    ]
