# Generated by Django 4.2.20 on 2025-05-31 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0035_remove_commonapprovalrequestsmodel_approved_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonApprovalPolicyModel',
        ),
    ]
