# Generated by Django 4.2.20 on 2025-06-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0036_alter_commontransititemsmodel_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commontransititemsmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='commontransititemsmodel',
            name='lenth',
        ),
        migrations.RemoveField(
            model_name='commontransititemsmodel',
            name='payer',
        ),
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
