# Generated by Django 4.2.20 on 2025-06-11 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0036_delete_commontransactioneventsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonassessmentsmodel',
            name='assessment_type',
        ),
        migrations.RemoveField(
            model_name='commonassessmentsmodel',
            name='charged_service',
        ),
        migrations.RemoveField(
            model_name='commonassessmentsmodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='commonassessmentsmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='commonassessmentsmodel',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='commonassessmentsmodel',
            name='order',
        ),
        migrations.RemoveField(
            model_name='commonassessmentsmodel',
            name='person_assessing',
        ),
        migrations.RemoveField(
            model_name='commonassessmentsmodel',
            name='term',
        ),
        migrations.RemoveField(
            model_name='commonassessmentsmodel',
            name='test_from',
        ),
        migrations.AddField(
            model_name='commonassessmentsmodel',
            name='staff_assessing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_assessing', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
        migrations.AddField(
            model_name='commonassessmentsmodel',
            name='trans_number',
            field=models.ForeignKey(blank=True, help_text='The encounter this triage record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mdclrcdobsv', to='allifmaalcommonapp.commontransactionsmodel'),
        ),
        migrations.AlterField(
            model_name='commonassessmentsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('AVAIL', 'Available'), ('OCC', 'Occupied'), ('RESERVED', 'Reserved'), ('CLEAN', 'Needs Cleaning')], default='ORD', help_text='Current status of the lab test.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='commonassessmentsmodel',
            name='test_for',
            field=models.ForeignKey(blank=True, help_text='The type of lab test ordered.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_orders', to='allifmaalcommonapp.commonstocksmodel'),
        ),
        migrations.DeleteModel(
            name='CommonAssessmentTypesModel',
        ),
    ]
