# Generated by Django 4.2.20 on 2025-05-18 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0036_commonquotesmodel_descriptionccdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonquotesmodel',
            name='descriptioncc',
        ),
        migrations.RemoveField(
            model_name='commonquotesmodel',
            name='descriptionccdf',
        ),
        migrations.RemoveField(
            model_name='commonquotesmodel',
            name='descriptionccdfd',
        ),
        migrations.AlterField(
            model_name='commonquotesmodel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crrncyqtes', to='allifmaalcommonapp.commoncurrenciesmodel'),
        ),
    ]
