# Generated by Django 4.2.20 on 2025-05-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0036_delete_commonapprovalpolicymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonapproversmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
