# Generated by Django 4.2.20 on 2025-05-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0037_commonapproversmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncreditnotesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting', 'waiting'), ('posted', 'posted')], default='waiting', max_length=50, null=True),
        ),
    ]
