# Generated by Django 4.2.20 on 2025-05-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0037_remove_commonquotesmodel_descriptioncc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='currency',
            field=models.CharField(choices=[('KES', 'KES'), ('$', 'USD'), ('£', 'EURO')], default='', max_length=20),
        ),
    ]
