# Generated by Django 4.2.20 on 2025-06-11 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0037_remove_commonassessmentsmodel_assessment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonassessmentsmodel',
            name='assessed_person',
        ),
        migrations.RemoveField(
            model_name='commonassessmentsmodel',
            name='operation_year',
        ),
        migrations.RemoveField(
            model_name='commonassessmentsmodel',
            name='staff_assessing',
        ),
    ]
