# Generated by Django 4.2.20 on 2025-06-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0037_remove_commontransititemsmodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
