# Generated by Django 4.2.20 on 2025-05-19 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0038_alter_commoninvoicesmodel_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoninvoicesmodel',
            name='currency',
        ),
    ]
