# Generated by Django 4.2.20 on 2025-06-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0038_commontransititemsmodel_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_dispatched_by_shipment_items', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='expected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
