# Generated by Django 4.2.20 on 2025-06-11 04:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0038_remove_commonassessmentsmodel_assessed_person_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommonAssessmentsModel',
            new_name='CommonTransactionItemsModel',
        ),
    ]
