# Generated by Django 4.2.20 on 2025-05-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0038_alter_commoncreditnotesmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncreditnotesmodel',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=50, null=True),
        ),
    ]
