# Generated by Django 4.2.20 on 2025-05-19 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0039_remove_commoninvoicesmodel_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoninvoicesmodel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crrncinv', to='allifmaalcommonapp.commoncurrenciesmodel'),
        ),
        migrations.AddField(
            model_name='commoninvoicesmodel',
            name='delivery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commoninvoicesmodel',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invpymnt', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
    ]
