# Generated by Django 4.2.20 on 2025-06-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0039_commontransititemsmodel_dispatched_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
