# Generated by Django 4.2.20 on 2025-06-02 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0039_commoncreditnotesmodel_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonapproversmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apprvrdept', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
    ]
