# Generated by Django 4.2.20 on 2025-06-11 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0039_rename_commonassessmentsmodel_commontransactionitemsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='blood_pressure_diastolic',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='blood_pressure_systolic',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='chief_complaints',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='complaints',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='current_medications_at_triage',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='height',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='known_chronic_conditions_triage',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='observation_date_time',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='oxygen_saturation',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='past_medical_history',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='pulse_rate',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='respiration_rate',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='treatment_plan',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='triage_date_time',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='weight',
        ),
        migrations.AddField(
            model_name='commontransactionsmodel',
            name='blood_pressure_diastolic',
            field=models.IntegerField(blank=True, help_text='Diastolic blood pressure (mmHg).', null=True),
        ),
        migrations.AddField(
            model_name='commontransactionsmodel',
            name='blood_pressure_systolic',
            field=models.IntegerField(blank=True, help_text='Systolic blood pressure (mmHg).', null=True),
        ),
        migrations.AddField(
            model_name='commontransactionsmodel',
            name='chief_complaints',
            field=models.TextField(blank=True, help_text="Patient's main symptoms or reason for visit.", null=True),
        ),
        migrations.AddField(
            model_name='commontransactionsmodel',
            name='complaints',
            field=models.CharField(blank=True, help_text="Patient's main symptoms or reason for visit.", max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='commontransactionsmodel',
            name='current_medications_at_triage',
            field=models.TextField(blank=True, help_text='Medications patient is currently taking, reported at triage.', null=True),
        ),
        migrations.AddField(
            model_name='commontransactionsmodel',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Patient's height in centimeters.", max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commontransactionsmodel',
            name='known_chronic_conditions_triage',
            field=models.TextField(blank=True, help_text="Patient's reported chronic conditions at triage.", null=True),
        ),
        migrations.AddField(
            model_name='commontransactionsmodel',
            name='oxygen_saturation',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="Patient's oxygen saturation (SpO2 %).", max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='commontransactionsmodel',
            name='past_medical_history',
            field=models.TextField(blank=True, help_text='Relevant past medical history provided by the patient.', null=True),
        ),
        migrations.AddField(
            model_name='commontransactionsmodel',
            name='pulse_rate',
            field=models.IntegerField(blank=True, help_text="Patient's pulse rate (beats per minute).", null=True),
        ),
        migrations.AddField(
            model_name='commontransactionsmodel',
            name='respiration_rate',
            field=models.IntegerField(blank=True, help_text="Patient's respiration rate (breaths per minute).", null=True),
        ),
        migrations.AddField(
            model_name='commontransactionsmodel',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Patient's temperature in Celsius.", max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='commontransactionsmodel',
            name='treatment_plan',
            field=models.TextField(blank=True, help_text='Treatment plan (medications, tests, referrals, follow-up).', null=True),
        ),
        migrations.AddField(
            model_name='commontransactionsmodel',
            name='triage_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='commontransactionsmodel',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.CreateModel(
            name='CommonAssessmentItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.TextField(blank=True, help_text="Doctor's assessment of the patient's condition.", null=True)),
                ('test_for', models.ForeignKey(blank=True, help_text='The type of lab test ordered.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_ordersss', to='allifmaalcommonapp.commonstocksmodel')),
                ('trans_number', models.ForeignKey(blank=True, help_text='The encounter this triage record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mdclrcdobsvs', to='allifmaalcommonapp.commontransactionsmodel')),
            ],
        ),
    ]
