# Generated by Django 4.2.20 on 2025-06-11 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0040_remove_commontransactionitemsmodel_assessment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commontopupcardsmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commontopupcardsmodel',
            name='card',
        ),
        migrations.RemoveField(
            model_name='commontopupcardsmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commontopupcardsmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commontopupcardsmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commontopupcardsmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='test_for',
        ),
        migrations.AddField(
            model_name='commontransactionitemsmodel',
            name='comments',
            field=models.TextField(blank=True, help_text="Doctor's assessment of the patient's condition.", null=True),
        ),
        migrations.AddField(
            model_name='commontransactionitemsmodel',
            name='items',
            field=models.ForeignKey(blank=True, help_text='The type of lab test ordered.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_orders', to='allifmaalcommonapp.commonstocksmodel'),
        ),
        migrations.DeleteModel(
            name='CommonAssessmentItemsModel',
        ),
        migrations.DeleteModel(
            name='CommonTopUpCardsModel',
        ),
    ]
