# Generated by Django 4.2.20 on 2025-06-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0040_commontransititemsmodel_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='commontransititemsmodel',
            name='delivered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
