# Generated by Django 4.2.20 on 2025-05-19 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0040_commoninvoicesmodel_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonjobsmodel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crrncjob', to='allifmaalcommonapp.commoncurrenciesmodel'),
        ),
        migrations.AddField(
            model_name='commonjobsmodel',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobpymtn', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
        migrations.AddField(
            model_name='commonsalariesmodel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crrnslries', to='allifmaalcommonapp.commoncurrenciesmodel'),
        ),
        migrations.AddField(
            model_name='commonsalariesmodel',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salripymtn', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
    ]
