# Generated by Django 4.2.20 on 2025-06-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0040_alter_commonapproversmodel_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonsectorsmodel',
            name='name',
            field=models.CharField(db_index=True, default='Sector Name', max_length=30, unique=True),
        ),
    ]
