# Generated by Django 4.2.20 on 2025-05-19 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0041_commonjobsmodel_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoninvoicesmodel',
            name='terms',
        ),
    ]
