# Generated by Django 4.2.20 on 2025-06-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0041_remove_commontopupcardsmodel_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commontransactionitemsmodel',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commontransactionitemsmodel',
            name='unitcost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='commontransactionitemsmodel',
            name='unitprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, null=True),
        ),
    ]
