# Generated by Django 4.2.20 on 2025-06-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0041_commontransititemsmodel_delivered_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='unitcost',
        ),
        migrations.RemoveField(
            model_name='commontransactionitemsmodel',
            name='unitprice',
        ),
    ]
