# Generated by Django 4.2.20 on 2025-06-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0042_remove_commontransactionitemsmodel_unitcost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commontransactionitemsmodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commontransactionitemsmodel',
            name='description',
            field=models.TextField(blank=True, help_text='Descriptions.', null=True),
        ),
        migrations.AlterField(
            model_name='commontransactionitemsmodel',
            name='comments',
            field=models.TextField(blank=True, help_text='general comments', null=True),
        ),
    ]
