# Generated by Django 4.2.20 on 2025-06-12 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0042_commontransactionitemsmodel_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonBuildingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('floors', models.CharField(blank=True, max_length=100, null=True)),
                ('units', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_occupancy', models.PositiveSmallIntegerField(blank=True, default=2, null=True)),
                ('amenities', models.TextField(blank=True, help_text='e.g., WiFi, AC, Balcony, Minibar', null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_room_type', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_room_type', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_room_type', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_room_types', to='allifmaalcommonapp.commondivisionsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_room_type', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommonSpacesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('room_type', models.CharField(blank=True, choices=[('AVAIL', 'Available'), ('OCC', 'Occupied'), ('MAINT', 'Maintenance'), ('DIRTY', 'Dirty')], default='AVAIL', max_length=10, null=True)),
                ('floor', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], null=True)),
                ('current_status', models.CharField(blank=True, choices=[('AVAIL', 'Available'), ('OCC', 'Occupied'), ('MAINT', 'Maintenance'), ('DIRTY', 'Dirty')], default='AVAIL', max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_occupancy', models.PositiveSmallIntegerField(blank=True, default=2, null=True)),
                ('amenities', models.TextField(blank=True, help_text='e.g., WiFi, AC, Balcony, Minibar', null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_rooms', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_rooms', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_rooms', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_rooms', to='allifmaalcommonapp.commondivisionsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='commonconstructionprojectsmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonconstructionprojectsmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonconstructionprojectsmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonconstructionprojectsmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonconstructionprojectsmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonconstructionprojectsmodel',
            name='project_manager',
        ),
        migrations.RemoveField(
            model_name='commonconstructionprojectsmodel',
            name='property',
        ),
        migrations.RemoveField(
            model_name='commoncreditdebitcardsmodel',
            name='bank_issued',
        ),
        migrations.RemoveField(
            model_name='commoncreditdebitcardsmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commoncreditdebitcardsmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commoncreditdebitcardsmodel',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='commoncreditdebitcardsmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commoncreditdebitcardsmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commoncreditdebitcardsmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonformsmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonformsmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonformsmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonformsmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonformsmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonleaseagreementsmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonleaseagreementsmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonleaseagreementsmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonleaseagreementsmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonleaseagreementsmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonleaseagreementsmodel',
            name='property',
        ),
        migrations.RemoveField(
            model_name='commonleaseagreementsmodel',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='commonleaseagreementsmodel',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='commonprojecttasksmodel',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='commonprojecttasksmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonprojecttasksmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonprojecttasksmodel',
            name='construction_project',
        ),
        migrations.RemoveField(
            model_name='commonprojecttasksmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonprojecttasksmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonprojecttasksmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonpropertiesmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonpropertiesmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonpropertiesmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonpropertiesmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonpropertiesmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonpropertiesmodel',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='commonpropertystatusmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonpropertystatusmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonpropertystatusmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonpropertystatusmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonpropertystatusmodel',
            name='listing_agent',
        ),
        migrations.RemoveField(
            model_name='commonpropertystatusmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonpropertystatusmodel',
            name='property',
        ),
        migrations.RemoveField(
            model_name='commonpropertyunitsmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonpropertyunitsmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonpropertyunitsmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonpropertyunitsmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonpropertyunitsmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonpropertyunitsmodel',
            name='property',
        ),
        migrations.RemoveField(
            model_name='commonresultsmodel',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='commonresultsmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonresultsmodel',
            name='charged_service',
        ),
        migrations.RemoveField(
            model_name='commonresultsmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonresultsmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonresultsmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonresultsmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonresultsmodel',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='commonresultsmodel',
            name='result_for_order',
        ),
        migrations.RemoveField(
            model_name='commonresultsmodel',
            name='result_given_by',
        ),
        migrations.RemoveField(
            model_name='commonresultsmodel',
            name='result_owner',
        ),
        migrations.RemoveField(
            model_name='commonresultsmodel',
            name='test_from',
        ),
        migrations.RemoveField(
            model_name='commonresultsmodel',
            name='validated_by',
        ),
        migrations.RemoveField(
            model_name='commonroomsmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonroomsmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonroomsmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonroomsmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonroomsmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonroomsmodel',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='commonroomtypesmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonroomtypesmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonroomtypesmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonroomtypesmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonroomtypesmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commontrackingmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commontrackingmodel',
            name='collected_by',
        ),
        migrations.RemoveField(
            model_name='commontrackingmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commontrackingmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commontrackingmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commontrackingmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commontrackingmodel',
            name='tracked_order',
        ),
        migrations.RemoveField(
            model_name='commoncustomersmodel',
            name='className',
        ),
        migrations.RemoveField(
            model_name='commoncustomersmodel',
            name='form',
        ),
        migrations.RemoveField(
            model_name='commoneventhallsmodel',
            name='room_type',
        ),
        migrations.DeleteModel(
            name='CommonClassesModel',
        ),
        migrations.DeleteModel(
            name='CommonConstructionProjectsModel',
        ),
        migrations.DeleteModel(
            name='CommonCreditDebitCardsModel',
        ),
        migrations.DeleteModel(
            name='CommonFormsModel',
        ),
        migrations.DeleteModel(
            name='CommonLeaseAgreementsModel',
        ),
        migrations.DeleteModel(
            name='CommonProjectTasksModel',
        ),
        migrations.DeleteModel(
            name='CommonPropertiesModel',
        ),
        migrations.DeleteModel(
            name='CommonPropertyStatusModel',
        ),
        migrations.DeleteModel(
            name='CommonPropertyUnitsModel',
        ),
        migrations.DeleteModel(
            name='CommonResultsModel',
        ),
        migrations.DeleteModel(
            name='CommonRoomTypesModel',
        ),
        migrations.DeleteModel(
            name='CommonTrackingModel',
        ),
        migrations.AlterField(
            model_name='commonroombookingsmodel',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='allifmaalcommonapp.commonspacesmodel'),
        ),
        migrations.DeleteModel(
            name='CommonRoomsModel',
        ),
    ]
