# Generated by Django 4.2.20 on 2025-05-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0042_remove_commoninvoicesmodel_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonpurchaseordersmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseordersmodel',
            name='taxamount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseordersmodel',
            name='uplift',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=20, null=True),
        ),
    ]
