# Generated by Django 4.2.20 on 2025-06-12 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0043_commonbuildingsmodel_commonspacesmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonRestaurantMenuItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(blank=True, default=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_menu_items', to='allifmaalcommonapp.commonbranchesmodel')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='allifmaalcommonapp.commoncategoriesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_menu_items', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_menu_items', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_menu_items', to='allifmaalcommonapp.commondivisionsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_menu_items', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='allifmaalcommonapp.commonrestaurantsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommonSpaceBookingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('check_in_date_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_date', models.DateTimeField(blank=True, null=True)),
                ('number_of_adults', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('number_of_children', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated total price for the stay', max_digits=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('PEND', 'Pending'), ('CONF', 'Confirmed'), ('CHECKIN', 'Checked-In'), ('CHECKOUT', 'Checked-Out'), ('CANCEL', 'Cancelled'), ('NOSHOW', 'No Show')], default='PEND', max_length=10, null=True)),
                ('booking_notes', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_room_booking', to='allifmaalcommonapp.commonbranchesmodel')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_custmr', to='allifmaalcommonapp.commoncustomersmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_room_booking', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_room_booking', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_room_booking', to='allifmaalcommonapp.commondivisionsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_room_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='CommonWarehouseItemsModel',
            new_name='CommonSpaceItemsModel',
        ),
        migrations.RemoveField(
            model_name='commoneventhallsmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commoneventhallsmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commoneventhallsmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commoneventhallsmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commoneventhallsmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonkitchenproductionsmodel',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='commonkitchenproductionsmodel',
            name='produced_by',
        ),
        migrations.RemoveField(
            model_name='commonkitchenproductionsmodel',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='commonmenucategoriesmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonmenucategoriesmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonmenucategoriesmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonmenucategoriesmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonmenucategoriesmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonmenucategoriesmodel',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='commonmenuitemsmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='commonmenuitemsmodel',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='commonrecipeingredientsmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonrecipeingredientsmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonrecipeingredientsmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonrecipeingredientsmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonrecipeingredientsmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonrecipeingredientsmodel',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='commonrecipeingredientsmodel',
            name='units',
        ),
        migrations.RemoveField(
            model_name='commonrecipesmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonrecipesmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonrecipesmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonrecipesmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonrecipesmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonrestaurantinvoice',
            name='common_invoice',
        ),
        migrations.RemoveField(
            model_name='commonrestaurantinvoice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='commonroombookingsmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonroombookingsmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonroombookingsmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonroombookingsmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonroombookingsmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='commonroombookingsmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonroombookingsmodel',
            name='room',
        ),
        migrations.RemoveField(
            model_name='commonwarehousesmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonwarehousesmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonwarehousesmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonwarehousesmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonwarehousesmodel',
            name='emplyee_in_charge',
        ),
        migrations.RemoveField(
            model_name='commonwarehousesmodel',
            name='inventory_account',
        ),
        migrations.RemoveField(
            model_name='commonwarehousesmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonspacesmodel',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='commonspacesmodel',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='commonspacesmodel',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='commonspacesmodel',
            name='room_type',
        ),
        migrations.AddField(
            model_name='commonrestaurantorderitemsmodel',
            name='stock_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_order_Restau', to='allifmaalcommonapp.commonstocksmodel'),
        ),
        migrations.AddField(
            model_name='commonrestauranttablesmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_restaurant_tables', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonrestauranttablesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_restaurant_tables', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonrestauranttablesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_restaurant_tables', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonrestauranttablesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_restaurant_tables', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonrestauranttablesmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_restaurant_tables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonspacesmodel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonspacesmodel',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_space', to='allifmaalcommonapp.commonassetsmodel'),
        ),
        migrations.AddField(
            model_name='commonspacesmodel',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Storage capacity in square meters', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commonspacesmodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commonspacesmodel',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commonspacesmodel',
            name='emplyee_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
        migrations.AddField(
            model_name='commonspacesmodel',
            name='inventory_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invaccwrhse', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
        migrations.AddField(
            model_name='commonspacesmodel',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commonspacesmodel',
            name='space_floor',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], null=True),
        ),
        migrations.AddField(
            model_name='commonspacesmodel',
            name='space_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commonspacesmodel',
            name='space_type',
            field=models.CharField(blank=True, choices=[('AVAIL', 'Available'), ('OCC', 'Occupied'), ('MAINT', 'Maintenance'), ('DIRTY', 'Dirty')], default='AVAIL', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='commoncreditnotesmodel',
            name='return_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allifmaalcommonapp.commonspacesmodel'),
        ),
        migrations.AlterField(
            model_name='commonshipmentsmodel',
            name='entry_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='allifmaalcommonapp.commonspacesmodel'),
        ),
        migrations.AlterField(
            model_name='commonshipmentsmodel',
            name='exit_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exits', to='allifmaalcommonapp.commonspacesmodel'),
        ),
        migrations.AlterField(
            model_name='commonspaceitemsmodel',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrhseitms', to='allifmaalcommonapp.commonspacesmodel'),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stckwarehouse', to='allifmaalcommonapp.commonspacesmodel'),
        ),
        migrations.AlterField(
            model_name='commonstocktransferordersmodel',
            name='from_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frmintcmpstcktrnsfrs', to='allifmaalcommonapp.commonspacesmodel'),
        ),
        migrations.AlterField(
            model_name='commonstocktransferordersmodel',
            name='to_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tointcmpstcktrnsfrs', to='allifmaalcommonapp.commonspacesmodel'),
        ),
        migrations.DeleteModel(
            name='CommonBuildingsModel',
        ),
        migrations.DeleteModel(
            name='CommonEventHallsModel',
        ),
        migrations.DeleteModel(
            name='CommonKitchenProductionsModel',
        ),
        migrations.DeleteModel(
            name='CommonMenuCategoriesModel',
        ),
        migrations.DeleteModel(
            name='CommonRecipeIngredientsModel',
        ),
        migrations.DeleteModel(
            name='CommonRecipesModel',
        ),
        migrations.DeleteModel(
            name='CommonRestaurantInvoice',
        ),
        migrations.DeleteModel(
            name='CommonRoomBookingsModel',
        ),
        migrations.DeleteModel(
            name='CommonWarehousesModel',
        ),
        migrations.AddField(
            model_name='commonspacebookingsmodel',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='allifmaalcommonapp.commonspacesmodel'),
        ),
        migrations.AddField(
            model_name='commonspacebookingsmodel',
            name='trans_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_bookings', to='allifmaalcommonapp.commontransactionsmodel'),
        ),
        migrations.AddField(
            model_name='commonrestaurantmenuitemsmodel',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_menu_items', to='allifmaalcommonapp.commonstocksmodel'),
        ),
        migrations.AlterField(
            model_name='commonrestaurantorderitemsmodel',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_items', to='allifmaalcommonapp.commonrestaurantmenuitemsmodel'),
        ),
        migrations.DeleteModel(
            name='CommonMenuItemsModel',
        ),
    ]
