# Generated by Django 4.2.20 on 2025-06-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0043_commontransactionitemsmodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commontransactionitemsmodel',
            name='comments',
            field=models.CharField(blank=True, help_text='general comments', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commontransactionitemsmodel',
            name='description',
            field=models.CharField(blank=True, help_text='Descriptions.', max_length=30, null=True),
        ),
    ]
