# Generated by Django 4.2.20 on 2025-06-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0044_alter_commontransactionitemsmodel_comments_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonBookingsModel',
        ),
        migrations.DeleteModel(
            name='CommonRestaurantMenuItemsModel',
        ),
        migrations.DeleteModel(
            name='CommonRestaurantOrderItemsModel',
        ),
        migrations.DeleteModel(
            name='CommonRestaurantOrdersModel',
        ),
        migrations.DeleteModel(
            name='CommonRestaurantsModel',
        ),
        migrations.DeleteModel(
            name='CommonRestaurantTablesModel',
        ),
    ]
