# Generated by Django 4.2.20 on 2025-06-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0044_commonrestaurantmenuitemsmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonspaceitemsmodel',
            old_name='warehouse',
            new_name='space',
        ),
        migrations.AlterUniqueTogether(
            name='commonspaceitemsmodel',
            unique_together={('items', 'space')},
        ),
    ]
