# Generated by Django 4.2.20 on 2025-05-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0045_alter_commonpurchaseordersmodel_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='annual_depreciation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='days_in_use',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='depreciated_by',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='lifespan',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='per_day_value_drop',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='salvage_value',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='value',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonbanksmodel',
            name='balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonbanksmodel',
            name='deposit',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonbanksmodel',
            name='withdrawal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonbankwithdrawalsmodel',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonchartofaccountsmodel',
            name='balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncustomerpaymentsmodel',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncustomersmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncustomersmodel',
            name='sales',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncustomersmodel',
            name='turnover',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncustomerstatementsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncustomerstatementsmodel',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncustomerstatementsmodel',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonemployeesmodel',
            name='salary',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonemployeesmodel',
            name='salary_balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonemployeesmodel',
            name='salary_payable',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonemployeesmodel',
            name='total_salary_paid',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonexpensesmodel',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonexpensesmodel',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commongeneralledgersmodel',
            name='balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoninvoiceitemsmodel',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoninvoiceitemsmodel',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='discountAmount',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='discountValue',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='grandtotal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='invoice_gross_profit',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='invoice_items_total_cost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='invoice_total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='tax',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='taxAmount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='totalwithdiscount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoninvoicesmodel',
            name='totalwithtax',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonledgerentriesmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonledgerentriesmodel',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonledgerentriesmodel',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonledgerentriesmodel',
            name='newamount',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonledgerentriesmodel',
            name='originalamount',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseorderitemsmodel',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseorderitemsmodel',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseorderitemsmodel',
            name='taxRate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseorderitemsmodel',
            name='unitcost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseordermisccostsmodel',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonpurchaseordermisccostsmodel',
            name='unitcost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonquoteitemsmodel',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonquoteitemsmodel',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonquotesmodel',
            name='discountAmount',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonquotesmodel',
            name='discountValue',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonquotesmodel',
            name='grandtotal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonquotesmodel',
            name='tax',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonquotesmodel',
            name='taxAmount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonquotesmodel',
            name='total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonquotesmodel',
            name='totalwithdiscount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonquotesmodel',
            name='totalwithtax',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonsalariesmodel',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonsalariesmodel',
            name='salary_payable',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='commonshareholderbankdepositsmodel',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='buyingPrice',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='criticalnumber',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='standardUnitCost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='unitPrice',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonstocksmodel',
            name='unitcost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonsupplierpaymentsmodel',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonsuppliersmodel',
            name='balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonsuppliersmodel',
            name='turnover',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonsupplierstatementsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonsupplierstatementsmodel',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commonsupplierstatementsmodel',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='commontaxparametersmodel',
            name='taxrate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True),
        ),
    ]
