# Generated by Django 4.2.20 on 2025-06-12 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0045_rename_warehouse_commonspaceitemsmodel_space_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assetcat', to='allifmaalcommonapp.commoncategoriesmodel'),
        ),
    ]
