# Generated by Django 4.2.20 on 2025-06-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0045_delete_commonbookingsmodel_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commonbranchesmodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='commondepartmentsmodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='commonbranchesmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commondepartmentsmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commondepartmentsmodel',
            name='division',
        ),
    ]
