# Generated by Django 4.2.20 on 2025-06-12 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0046_alter_commonassetsmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonassetsmodel',
            name='employee_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asstemply', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
    ]
