# Generated by Django 4.2.20 on 2025-06-12 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0047_alter_commonassetsmodel_employee_in_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonBookingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('check_in_date_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_date', models.DateTimeField(blank=True, null=True)),
                ('number_of_adults', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('number_of_children', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated total price for the stay', max_digits=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('PEND', 'Pending'), ('CONF', 'Confirmed'), ('CHECKIN', 'Checked-In'), ('CHECKOUT', 'Checked-Out'), ('CANCEL', 'Cancelled'), ('NOSHOW', 'No Show')], default='PEND', max_length=10, null=True)),
                ('booking_notes', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_room_booking', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_room_booking', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_room_booking', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_room_booking', to='allifmaalcommonapp.commondivisionsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_room_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommonSpaceBookingItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='inventory_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invaccwrhse', to='allifmaalcommonapp.commonchartofaccountsmodel'),
        ),
        migrations.AlterField(
            model_name='commontransactionsmodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commontransactionsmodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commontransactionsmodel',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CommonSpaceBookingsModel',
        ),
        migrations.AddField(
            model_name='commonspacebookingitemsmodel',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='allifmaalcommonapp.commonspacesmodel'),
        ),
        migrations.AddField(
            model_name='commonbookingsmodel',
            name='trans_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_bookings', to='allifmaalcommonapp.commontransactionsmodel'),
        ),
    ]
