# Generated by Django 4.2.20 on 2025-06-28 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0047_commonbranchesmodel_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
