# Generated by Django 4.2.20 on 2025-06-12 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0048_commonbookingsmodel_commonspacebookingitemsmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonspacebookingitemsmodel',
            name='trans_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_bookings_items', to='allifmaalcommonapp.commontransactionsmodel'),
        ),
    ]
