# Generated by Django 4.2.20 on 2025-06-28 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0048_alter_commoncompanyscopemodel_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='ends',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='starts',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='comments',
            field=models.CharField(blank=True, default='scope comments', max_length=30),
        ),
    ]
