# Generated by Django 4.2.20 on 2025-06-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0049_commoncompanyscopemodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='comments',
            field=models.CharField(blank=True, default='comments', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='description',
            field=models.CharField(blank=True, default='description', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='ends',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='starts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
