# Generated by Django 4.2.20 on 2025-06-13 06:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0050_remove_commonmaintenanceassignmentsmodel_assigned_to_employee_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommonShipmentItemsModel',
            new_name='CommonTransitItemsModel',
        ),
        migrations.RenameModel(
            old_name='CommonShipmentsModel',
            new_name='CommonTransitModel',
        ),
        migrations.DeleteModel(
            name='CommonRoutesModel',
        ),
    ]
