# Generated by Django 4.2.20 on 2025-06-28 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0050_alter_commoncompanyscopemodel_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='status',
            field=models.CharField(blank=True, choices=[('AVAIL', 'Available'), ('OCC', 'Occupied'), ('RESERVED', 'Reserved'), ('CLEAN', 'Needs Cleaning')], default='Draft', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='comments',
            field=models.TextField(blank=True, default='comments', null=True),
        ),
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='description',
            field=models.TextField(blank=True, default='description', null=True),
        ),
    ]
