# Generated by Django 4.2.20 on 2025-06-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0051_commoncompanyscopemodel_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoncompanyscopemodel',
            name='uuid',
        ),
    ]
