# Generated by Django 4.2.20 on 2025-06-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0051_rename_commonshipmentitemsmodel_commontransititemsmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commontransitmodel',
            name='delivery_notes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
