# Generated by Django 4.2.20 on 2025-06-13 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0052_alter_commontransitmodel_delivery_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commontransitmodel',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_supplied', to='allifmaalcommonapp.commonsuppliersmodel'),
        ),
    ]
