# Generated by Django 4.2.20 on 2025-06-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0052_remove_commoncompanyscopemodel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='name',
            field=models.CharField(blank=True, default='Your Scope', max_length=30, null=True),
        ),
    ]
