# Generated by Django 4.2.20 on 2025-06-28 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0053_alter_commoncompanyscopemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
