# Generated by Django 4.2.20 on 2025-06-28 14:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0054_commoncompanyscopemodel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Archived', 'Archived')], default='Draft', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
