# Generated by Django 4.2.20 on 2025-06-13 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0054_commoncodesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonspacesmodel',
            name='area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commonspacesmodel',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, help_text='Is this unit currently available for rent/sale?', null=True),
        ),
        migrations.AddField(
            model_name='commonspacesmodel',
            name='number_of_bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonspacesmodel',
            name='number_of_bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonspacesmodel',
            name='rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rental price for the unit', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commonspacesmodel',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('APT', 'Apartment'), ('ROOM', 'ROOM'), ('SHOP', 'Shop'), ('OFFICE', 'Office'), ('HOUSE', 'House'), ('WAREHOUSE', 'Warehouse'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnch_property_unit_types', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmp_property_unit_types', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_property_unit_types', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvs_property_unit_types', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownr_property_unit_types', to=settings.AUTH_USER_MODEL),
        ),
    ]
