# Generated by Django 4.2.20 on 2025-06-13 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0055_commonspacesmodel_area_sqft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_rooms', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_rooms', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_rooms', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_rooms', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AlterField(
            model_name='commonspacesmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CommonSpaceUnitsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_number', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('space_type', models.CharField(blank=True, choices=[('AVAIL', 'Available'), ('OCC', 'Occupied'), ('MAINT', 'Maintenance'), ('DIRTY', 'Dirty')], default='AVAIL', max_length=10, null=True)),
                ('space_floor', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], null=True)),
                ('current_status', models.CharField(blank=True, choices=[('AVAIL', 'Available'), ('OCC', 'Occupied'), ('MAINT', 'Maintenance'), ('DIRTY', 'Dirty')], default='AVAIL', max_length=10, null=True)),
                ('base_price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_occupancy', models.PositiveSmallIntegerField(blank=True, default=2, null=True)),
                ('amenities', models.TextField(blank=True, help_text='e.g., WiFi, AC, Balcony, Minibar', null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Storage capacity in square meters', max_digits=10, null=True)),
                ('unit_type', models.CharField(blank=True, choices=[('APT', 'Apartment'), ('ROOM', 'ROOM'), ('SHOP', 'Shop'), ('OFFICE', 'Office'), ('HOUSE', 'House'), ('WAREHOUSE', 'Warehouse'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rental_price', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rental price for the unit', max_digits=10, null=True)),
                ('is_available', models.BooleanField(blank=True, default=True, help_text='Is this unit currently available for rent/sale?', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_space_units', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_space_units', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_space_units', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_space_units', to='allifmaalcommonapp.commondivisionsmodel')),
                ('emplyee_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speces_units_staff', to='allifmaalcommonapp.commonemployeesmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_space_units', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units_space', to='allifmaalcommonapp.commonspacesmodel')),
            ],
        ),
    ]
