# Generated by Django 4.2.20 on 2025-06-13 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0056_alter_commonspacesmodel_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonProgressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('recording_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('recorded_on', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchvtlsgns', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmpvtlsgns', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptvtlsgns', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsvtlsgns', to='allifmaalcommonapp.commondivisionsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownvtlsgns', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='The nurse or staff member who recorded the vital signs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refering_nurse', to='allifmaalcommonapp.commonemployeesmodel')),
                ('trans_number', models.ForeignKey(blank=True, help_text='The encounter this vital signs record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='allifmaalcommonapp.commontransactionsmodel')),
            ],
        ),
    ]
