# Generated by Django 4.2.20 on 2025-06-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0056_commoncompanyscopemodel_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='delete_status',
            field=models.CharField(blank=True, choices=[('undeletable', 'undeletable'), ('deletable', 'deletable')], default='undeletable', max_length=30, null=True),
        ),
    ]
