# Generated by Django 4.2.20 on 2025-06-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0057_commoncompanyscopemodel_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncompanydetailsmodel',
            name='can_delete',
            field=models.CharField(blank=True, choices=[('Undeletable', 'Undeletable'), ('Deletable', 'Deletable')], default='undeletable', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='delete_status',
            field=models.CharField(blank=True, choices=[('Undeletable', 'Undeletable'), ('Deletable', 'Deletable')], default='Undeletable', max_length=30, null=True),
        ),
    ]
