# Generated by Django 4.2.20 on 2025-06-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0058_alter_commoncompanydetailsmodel_can_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='delete_status',
            field=models.CharField(blank=True, choices=[('Undeletable', 'Undeletable'), ('Deletable', 'Deletable')], default='Deletable', max_length=30, null=True),
        ),
    ]
