# Generated by Django 4.2.20 on 2025-06-28 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0060_alter_commoncompanyscopemodel_starts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='ends',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
