# Generated by Django 4.2.20 on 2025-06-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0061_alter_commoncompanyscopemodel_ends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='comments',
            field=models.TextField(blank=True, default='Comments', null=True),
        ),
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='description',
            field=models.TextField(blank=True, default='Description', null=True),
        ),
    ]
