# Generated by Django 4.2.20 on 2025-06-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0062_alter_commoncompanyscopemodel_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='reference',
            field=models.CharField(blank=True, db_index=True, help_text='An optional identifier from an external system or an internal reference code.', max_length=100, null=True),
        ),
    ]
