# Generated by Django 4.2.20 on 2025-06-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0064_alter_commoncompanyscopemodel_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commoncompanyscopemodel',
            old_name='name',
            new_name='scope_name',
        ),
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='scope_assumptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='scope_constraints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='scope_exclusions',
            field=models.TextField(blank=True, help_text='Specific items, features, or activities that are explicitly excluded from this scope.', null=True),
        ),
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='scope_resources',
            field=models.TextField(blank=True, help_text='Resources required by this particular scope', null=True),
        ),
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='scope_risks',
            field=models.TextField(blank=True, help_text='A summary of identified risks associated with this scope.', null=True),
        ),
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='scope_stakeholders',
            field=models.TextField(blank=True, help_text='Key individuals or groups affected by or having an interest in this scope.', null=True),
        ),
        migrations.AddField(
            model_name='commoncompanyscopemodel',
            name='scope_type',
            field=models.CharField(blank=True, choices=[('Project', 'Project Scope'), ('Product', 'Product Scope'), ('Service', 'Service Scope'), ('Departmental', 'Departmental Scope'), ('Organizational', 'Organizational Scope'), ('Other', 'Other')], max_length=30, null=True),
        ),
    ]
