# Generated by Django 4.2.20 on 2025-06-28 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0065_rename_name_commoncompanyscopemodel_scope_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commoncompanyscopemodel',
            old_name='scope_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='comments',
            field=models.TextField(blank=True, default='Comments', null=True),
        ),
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='delete_status',
            field=models.CharField(blank=True, choices=[('Undeletable', 'Undeletable'), ('Deletable', 'Deletable')], default='Deletable', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='description',
            field=models.TextField(blank=True, default='Description', null=True),
        ),
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='ends',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='name',
            field=models.CharField(blank=True, default='Your Scope', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='priority',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Urgent', 'Urgent')], default='Normal', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='reference', help_text='An optional identifier from an external system or an internal reference code.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='starts',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Draft', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commontaxparametersmodel',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commontaxparametersmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AlterField(
            model_name='commontaxparametersmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='commontaxparametersmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AlterField(
            model_name='commontaxparametersmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AlterField(
            model_name='commontaxparametersmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
