# Generated by Django 4.2.20 on 2025-06-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0067_alter_commoncompanyscopemodel_ends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commontaxparametersmodel',
            name='taxdescription',
        ),
        migrations.RemoveField(
            model_name='commontaxparametersmodel',
            name='taxname',
        ),
        migrations.AlterField(
            model_name='commoncompanyscopemodel',
            name='name',
            field=models.CharField(blank=True, default='Name', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commontaxparametersmodel',
            name='name',
            field=models.CharField(blank=True, default='Name', max_length=30, null=True),
        ),
    ]
