# Generated by Django 4.2.20 on 2025-06-12 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0043_commonbuildingsmodel_commonspacesmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonConstructionProjectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('current_cost', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=15, null=True)),
                ('status', models.CharField(blank=True, choices=[('PLAN', 'Planned'), ('INPR', 'In Progress'), ('PAUSE', 'Paused'), ('SCHED', 'Scheduled'), ('COMP', 'Completed'), ('CANC', 'Cancelled')], default='PLAN', max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnch_prject', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmp_prject', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_prject', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvs_prject', to='allifmaalcommonapp.commondivisionsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownr_prject', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='allifmaalcommonapp.commonemployeesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommonPropertiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Common name or identifier for the property (e.g., 'Maple Apartments', 'Downtown Mall')", max_length=255, null=True)),
                ('address', models.TextField(blank=True, help_text='Full street address of the property', null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, default='Somalia', max_length=100, null=True)),
                ('total_area_sqft', models.DecimalField(blank=True, decimal_places=2, help_text='Total area of the property in square feet', max_digits=10, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Is this property currently managed?', null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnch_properties', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmp_properties', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_properties', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvs_properties', to='allifmaalcommonapp.commondivisionsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownr_properties', to=settings.AUTH_USER_MODEL)),
                ('property_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_properties', to='allifmaalcommonapp.commoncategoriesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommonPropertyUnitsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(blank=True, help_text="Unique identifier for the unit within the property (e.g., '101', 'Shop A5')", max_length=50, null=True)),
                ('unit_type', models.CharField(blank=True, choices=[('APT', 'Apartment'), ('ROOM', 'ROOM'), ('SHOP', 'Shop'), ('OFFICE', 'Office'), ('HOUSE', 'House'), ('WAREHOUSE', 'Warehouse'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('number_of_bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('number_of_bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rental_price', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rental price for the unit', max_digits=10, null=True)),
                ('is_available', models.BooleanField(blank=True, default=True, help_text='Is this unit currently available for rent/sale?', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnch_property_unit_types', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmp_property_unit_types', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_property_unit_types', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvs_property_unit_types', to='allifmaalcommonapp.commondivisionsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownr_property_unit_types', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='allifmaalrealestateapp.commonpropertiesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommonProjectTasksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('AVAIL', 'Available'), ('OCC', 'Occupied'), ('RESERVED', 'Reserved'), ('CLEAN', 'Needs Cleaning')], max_length=10, null=True)),
                ('priority_level', models.CharField(blank=True, choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('URGENT', 'Urgent')], max_length=10, null=True)),
                ('spares_cost', models.IntegerField(blank=True, default=0, null=True)),
                ('labor_cost', models.IntegerField(blank=True, default=0, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='allifmaalcommonapp.commonemployeesmodel')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks_branch', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks_company', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('construction_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='allifmaalrealestateapp.commonconstructionprojectsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks_dept', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks_division', to='allifmaalcommonapp.commondivisionsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommonLeaseAgreementsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10, null=True)),
                ('payment_due_day', models.PositiveSmallIntegerField(blank=True, default=1, help_text='Day of the month rent is due (e.g., 1 for 1st of month)', null=True)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnch_lease_agrement', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmp_lease_agrement', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_lease_agrement', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvs_lease_agrement', to='allifmaalcommonapp.commondivisionsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownr_lease_agrement', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, help_text='The property being leased (if a whole property or land)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='allifmaalrealestateapp.commonpropertiesmodel')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='allifmaalcommonapp.commoncustomersmodel')),
                ('unit', models.ForeignKey(blank=True, help_text='The specific unit being leased (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='allifmaalrealestateapp.commonpropertyunitsmodel')),
            ],
        ),
        migrations.AddField(
            model_name='commonconstructionprojectsmodel',
            name='property',
            field=models.ForeignKey(blank=True, help_text='The property where construction is taking place', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='construction_projects', to='allifmaalrealestateapp.commonpropertiesmodel'),
        ),
    ]
