# Generated by Django 4.2.20 on 2025-06-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalrealestateapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonpropertyunitsmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonpropertyunitsmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonpropertyunitsmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonpropertyunitsmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonpropertyunitsmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonpropertyunitsmodel',
            name='property',
        ),
        migrations.RemoveField(
            model_name='commonconstructionprojectsmodel',
            name='property',
        ),
        migrations.RemoveField(
            model_name='commonleaseagreementsmodel',
            name='property',
        ),
        migrations.RemoveField(
            model_name='commonleaseagreementsmodel',
            name='unit',
        ),
        migrations.DeleteModel(
            name='CommonPropertiesModel',
        ),
        migrations.DeleteModel(
            name='CommonPropertyUnitsModel',
        ),
    ]
