# Generated by Django 4.2.20 on 2025-06-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalrealestateapp', '0002_remove_commonpropertyunitsmodel_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonleaseagreementsmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonleaseagreementsmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonleaseagreementsmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonleaseagreementsmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonleaseagreementsmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commonleaseagreementsmodel',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='commonprojecttasksmodel',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='commonprojecttasksmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonprojecttasksmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonprojecttasksmodel',
            name='construction_project',
        ),
        migrations.RemoveField(
            model_name='commonprojecttasksmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonprojecttasksmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonprojecttasksmodel',
            name='owner',
        ),
        migrations.DeleteModel(
            name='CommonConstructionProjectsModel',
        ),
        migrations.DeleteModel(
            name='CommonLeaseAgreementsModel',
        ),
        migrations.DeleteModel(
            name='CommonProjectTasksModel',
        ),
    ]
