# Generated by Django 4.2.20 on 2025-06-14 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allifmaalcommonapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Type of referral (Internal or External).', max_length=50, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True, help_text='Date and time of patient admission.', null=True)),
                ('reason_for_admission', models.TextField(blank=True, help_text='The primary reason for patient admission.', max_length=250, null=True)),
                ('status', models.CharField(choices=[('ADM', 'Admitted'), ('DIS', 'Discharged'), ('TRANS', 'Transferred'), ('AWD', 'Absconded Without Discharge')], default='ADM', help_text='Current status of the admission (e.g., Admitted, Discharged).', max_length=100)),
                ('admission_date_time', models.DateTimeField(blank=True, help_text='Date and time of patient discharge (if applicable).', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DischargesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_summary', models.CharField(blank=True, max_length=250, null=True)),
                ('discharge_diagnosis', models.CharField(blank=True, max_length=250, null=True)),
                ('medications_at_discharge', models.CharField(blank=True, max_length=250, null=True)),
                ('follow_up_plan', models.CharField(blank=True, max_length=250, null=True)),
                ('recorded_on', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAdministrationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage_value', models.DecimalField(blank=True, decimal_places=2, help_text="The actual dosage administered (e.g., '500').", max_digits=10, null=True)),
                ('dosage_unit', models.CharField(blank=True, choices=[('MG', 'Milligrams'), ('G', 'Grams'), ('ML', 'Milliliters'), ('UNIT', 'Units'), ('PIECE', 'Pieces'), ('DROP', 'Drops'), ('MCG', 'Micrograms')], help_text="The unit of the administered dosage (e.g., 'MG', 'ML').", max_length=10, null=True)),
                ('via', models.CharField(blank=True, choices=[('ORAL', 'Oral'), ('IM', 'Intramuscular Injection'), ('IV', 'Intravenous Injection'), ('INHAL', 'Inhalation'), ('TOPIC', 'Topical'), ('SUBQ', 'Subcutaneous')], help_text='The route by which the medication was administered.', max_length=10, null=True)),
                ('comments', models.TextField(blank=True, help_text='Any additional comments about the administration.', null=True)),
                ('administration_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('given_on', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage_form', models.CharField(blank=True, choices=[('TAB', 'Tablet'), ('SYR', 'Syrup'), ('CAP', 'Capsule'), ('INJ', 'Injection'), ('CREAM', 'Cream'), ('DROPS', 'Drops'), ('OTH', 'Other')], default='Please select', help_text='Formulation of the drug (e.g., Tablet, Syrup, Injection).', max_length=200, null=True)),
                ('dosage', models.CharField(blank=True, choices=[('MG', 'Milligrams'), ('G', 'Grams'), ('ML', 'Milliliters'), ('UNIT', 'Units'), ('PIECE', 'Pieces'), ('DROP', 'Drops'), ('MCG', 'Micrograms')], help_text="Dosage amount and unit (e.g., '500mg', '10ml').", max_length=250, null=True)),
                ('via', models.CharField(blank=True, choices=[('ORAL', 'Oral'), ('IM', 'Intramuscular Injection'), ('IV', 'Intravenous Injection'), ('INHAL', 'Inhalation'), ('TOPIC', 'Topical'), ('SUBQ', 'Subcutaneous')], default='ORAL', help_text='How the medication should be administered (e.g., Oral, IV, IM).', max_length=250, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True)),
                ('is_issued', models.BooleanField(default=False, help_text='True if the prescription has been dispensed by the pharmacy.', max_length=50)),
                ('frequency', models.CharField(blank=True, max_length=350, null=True)),
                ('duration', models.CharField(blank=True, max_length=350, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Patient-specific instructions for medication use.', null=True)),
                ('issued_date_time', models.DateTimeField(blank=True, help_text='Date and time when the prescription was dispensed.', null=True)),
                ('prescription_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_referral', models.CharField(blank=True, help_text='The reason for the referral.', max_length=250, null=True)),
                ('referred_on', models.DateField(blank=True, null=True)),
                ('referral_type', models.CharField(choices=[('INT', 'Internal'), ('EXT', 'External')], default='INT', help_text='Type of referral (Internal or External).', max_length=10)),
                ('status', models.CharField(choices=[('PEND', 'Pending'), ('ACC', 'Accepted'), ('REJ', 'Rejected'), ('COMP', 'Completed')], default='PEND', help_text='Current status of the referral.', max_length=10)),
                ('referral_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brncharefrals', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmprefrals', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptrefrals', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsrefrals', to='allifmaalcommonapp.commondivisionsmodel')),
                ('medical_file', models.ForeignKey(blank=True, help_text='The encounter this referral belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_medfile', to='allifmaalcommonapp.commontransactionsmodel')),
            ],
        ),
    ]
