# Generated by Django 4.2.20 on 2025-09-06 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allifmaalcommonapp', '0001_initial'),
        ('allifmaalshaafiapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='triagesmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triagesmodel',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='The main employee attending this encounter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='en_triage', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
        migrations.AddField(
            model_name='triagesmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='referralsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='referralsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='referralsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='referralsmodel',
            name='medical_file',
            field=models.ForeignKey(blank=True, help_text='The encounter this referral belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_medfile', to='allifmaalcommonapp.commontransactionsmodel'),
        ),
        migrations.AddField(
            model_name='referralsmodel',
            name='operation_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonoperationyeartermsmodel'),
        ),
        migrations.AddField(
            model_name='referralsmodel',
            name='operation_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonoperationyearsmodel'),
        ),
        migrations.AddField(
            model_name='referralsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralsmodel',
            name='referred_to_doctor',
            field=models.ForeignKey(blank=True, help_text='The doctor to whom the patient is referred (if internal).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_referrals', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
        migrations.AddField(
            model_name='referralsmodel',
            name='referred_to_external_organization',
            field=models.ForeignKey(blank=True, help_text='Name of the external organization/clinic referred to (if external referral).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='allifmaalcommonapp.commonsuppliersmodel'),
        ),
        migrations.AddField(
            model_name='referralsmodel',
            name='referring_doctor',
            field=models.ForeignKey(blank=True, help_text='The doctor issuing the referral.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referring_doctor', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
        migrations.AddField(
            model_name='referralsmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='medicationsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='medicationsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='medicationsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='medicationsmodel',
            name='issued_by_pharmacist',
            field=models.ForeignKey(blank=True, help_text='The pharmacist who dispensed the medication (if dispensed).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
        migrations.AddField(
            model_name='medicationsmodel',
            name='medical_file',
            field=models.ForeignKey(blank=True, help_text='The encounter this prescription belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='allifmaalcommonapp.commontransactionsmodel'),
        ),
        migrations.AddField(
            model_name='medicationsmodel',
            name='medication',
            field=models.ForeignKey(blank=True, help_text='The drug/item prescribed (from common inventory).', max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='allifmaalcommonapp.commonstocksmodel'),
        ),
        migrations.AddField(
            model_name='medicationsmodel',
            name='operation_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonoperationyeartermsmodel'),
        ),
        migrations.AddField(
            model_name='medicationsmodel',
            name='operation_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonoperationyearsmodel'),
        ),
        migrations.AddField(
            model_name='medicationsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationsmodel',
            name='prescribed_by_doctor',
            field=models.ForeignKey(blank=True, help_text='The doctor who issued this prescription.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_prescriptions', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
        migrations.AddField(
            model_name='medicationsmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicaladministrationsmodel',
            name='administered_by_nurse',
            field=models.ForeignKey(blank=True, help_text='The nurse or staff member who administered the medication.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_medications', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
        migrations.AddField(
            model_name='medicaladministrationsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='medicaladministrationsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='medicaladministrationsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='medicaladministrationsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='medicaladministrationsmodel',
            name='operation_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonoperationyeartermsmodel'),
        ),
        migrations.AddField(
            model_name='medicaladministrationsmodel',
            name='operation_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonoperationyearsmodel'),
        ),
        migrations.AddField(
            model_name='medicaladministrationsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicaladministrationsmodel',
            name='prescription',
            field=models.ForeignKey(blank=True, help_text='The prescription being administered (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrations', to='allifmaalshaafiapp.medicationsmodel'),
        ),
        migrations.AddField(
            model_name='medicaladministrationsmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dischargesmodel',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dschrgsummryadmsn', to='allifmaalshaafiapp.admissionsmodel'),
        ),
        migrations.AddField(
            model_name='dischargesmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='dischargesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='dischargesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='dischargesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='dischargesmodel',
            name='operation_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonoperationyeartermsmodel'),
        ),
        migrations.AddField(
            model_name='dischargesmodel',
            name='operation_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonoperationyearsmodel'),
        ),
        migrations.AddField(
            model_name='dischargesmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dischargesmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='assessmentsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='assessmentsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='assessmentsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='assessmentsmodel',
            name='medical_file',
            field=models.ForeignKey(blank=True, help_text='The customer associated with this encounter.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fileassessemnt', to='allifmaalcommonapp.commontransactionsmodel'),
        ),
        migrations.AddField(
            model_name='assessmentsmodel',
            name='operation_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonoperationyeartermsmodel'),
        ),
        migrations.AddField(
            model_name='assessmentsmodel',
            name='operation_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonoperationyearsmodel'),
        ),
        migrations.AddField(
            model_name='assessmentsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentsmodel',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='The main employee attending this encounter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='en_assessment', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
        migrations.AddField(
            model_name='assessmentsmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='admitting_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_patients', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='bed',
            field=models.ForeignKey(blank=True, help_text='The specific bed allocated to the patient.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='allifmaalcommonapp.commonspaceunitsmodel'),
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='medical_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mdcladmnss', to='allifmaalcommonapp.commontransactionsmodel'),
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='operation_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonoperationyeartermsmodel'),
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='operation_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonoperationyearsmodel'),
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='ward',
            field=models.ForeignKey(blank=True, help_text='The ward to which the patient is admitted.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='allifmaalcommonapp.commonspacesmodel'),
        ),
    ]
