# Generated by Django 4.2.20 on 2025-06-14 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalshaafiapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_referalls', to=settings.AUTH_USER_MODEL),
        ),
    ]
