# Generated by Django 4.2.20 on 2025-07-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triagesmodel',
            options={'ordering': ['-date']},
        ),
    ]
