# Generated by Django 4.2.20 on 2025-07-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagesmodel',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
