# Generated by Django 4.2.20 on 2025-08-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestrequestsmodel',
            name='date_time',
        ),
        migrations.AddField(
            model_name='labtestrequestsmodel',
            name='test_status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Collected', 'Sample Collected'), ('Processing', 'Under Processing'), ('Completed', 'Completed'), ('Validated', 'Validated'), ('Resulted', 'Results Available'), ('Pending', 'Pending Collection'), ('Cancelled', 'Cancelled'), ('Lost', 'Lost')], default='Blood', help_text='Current status of the lab order.', max_length=50),
        ),
        migrations.AlterField(
            model_name='labtestrequestsmodel',
            name='comments',
            field=models.TextField(blank=True, default='Comments', null=True),
        ),
        migrations.AlterField(
            model_name='labtestrequestsmodel',
            name='description',
            field=models.TextField(blank=True, default='Description', null=True),
        ),
        migrations.AlterField(
            model_name='labtestrequestsmodel',
            name='priority',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Urgent', 'Urgent')], default='Normal', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labtestrequestsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
    ]
