# Generated by Django 4.2.20 on 2025-06-09 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0004_alter_commonoperationyearsmodel_department_and_more'),
        ('allifmaalshaafiapp', '0002_alter_nursingnotesmodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmpwardsrelatnme', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
    ]
