# Generated by Django 4.2.20 on 2025-07-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0003_remove_triagesmodel_record_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagesmodel',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
