# Generated by Django 4.2.20 on 2025-06-20 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0018_remove_commontransactionsmodel_blood_pressure_diastolic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalshaafiapp', '0003_alter_referralsmodel_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triage_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('complaints', models.CharField(blank=True, help_text="Patient's main symptoms or reason for visit.", max_length=250, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text="Patient's height in centimeters.", max_digits=30, null=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, help_text='Systolic blood pressure (mmHg).', null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, help_text='Diastolic blood pressure (mmHg).', null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text="Patient's temperature in Celsius.", max_digits=4, null=True)),
                ('pulse_rate', models.IntegerField(blank=True, help_text="Patient's pulse rate (beats per minute).", null=True)),
                ('respiration_rate', models.IntegerField(blank=True, help_text="Patient's respiration rate (breaths per minute).", null=True)),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=1, help_text="Patient's oxygen saturation (SpO2 %).", max_digits=4, null=True)),
                ('past_medical_history', models.TextField(blank=True, help_text='Relevant past medical history provided by the patient.', null=True)),
                ('known_chronic_conditions_triage', models.TextField(blank=True, help_text="Patient's reported chronic conditions at triage.", null=True)),
                ('current_medications_at_triage', models.TextField(blank=True, help_text='Medications patient is currently taking, reported at triage.', null=True)),
                ('treatment_plan', models.TextField(blank=True, help_text='Treatment plan (medications, tests, referrals, follow-up).', null=True)),
                ('employee_in_charge', models.ForeignKey(blank=True, help_text='The main employee attending this encounter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='en_triage', to='allifmaalcommonapp.commonemployeesmodel')),
                ('medical_file', models.ForeignKey(blank=True, help_text='The customer associated with this encounter.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filetranige', to='allifmaalcommonapp.commontransactionsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_encounters_triage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
