# Generated by Django 4.2.20 on 2025-08-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0003_admissionsmodel_ratings_assessmentsmodel_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dischargesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicaladministrationsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicationsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='referralsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='triagesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
    ]
