# Generated by Django 4.2.20 on 2025-06-09 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0014_remove_commonprogramsmodel_is_active_and_more'),
        ('allifmaalshaafiapp', '0003_alter_wardsmodel_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchprescrptn', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
    ]
