# Generated by Django 4.2.20 on 2025-08-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0003_remove_labtestrequestsmodel_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestrequestsmodel',
            name='test_status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Collected', 'Sample Collected'), ('Processing', 'Under Processing'), ('Completed', 'Completed'), ('Validated', 'Validated'), ('Resulted', 'Results Available'), ('Pending', 'Pending Collection'), ('Cancelled', 'Cancelled'), ('Lost', 'Lost')], default='Ordered', help_text='Current status of the lab order.', max_length=50),
        ),
    ]
