# Generated by Django 4.2.20 on 2025-07-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0003_alter_triagesmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triagesmodel',
            options={'ordering': ['-temperature']},
        ),
    ]
