# Generated by Django 4.2.20 on 2025-06-22 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0045_delete_commonbookingsmodel_and_more'),
        ('allifmaalshaafiapp', '0004_triagesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagesmodel',
            name='current_medications_at_triage',
        ),
        migrations.RemoveField(
            model_name='triagesmodel',
            name='employee_in_charge',
        ),
        migrations.RemoveField(
            model_name='triagesmodel',
            name='known_chronic_conditions_triage',
        ),
        migrations.RemoveField(
            model_name='triagesmodel',
            name='triage_date',
        ),
        migrations.AddField(
            model_name='triagesmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnch_triage', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='triagesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmp_triage', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='triagesmodel',
            name='current_medication',
            field=models.TextField(blank=True, help_text='Medications patient is currently taking, reported at triage.', null=True),
        ),
        migrations.AddField(
            model_name='triagesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_triage', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='triagesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvs_triage', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='triagesmodel',
            name='known_chronic_conditions',
            field=models.TextField(blank=True, help_text="Patient's reported chronic conditions at triage.", null=True),
        ),
        migrations.AddField(
            model_name='triagesmodel',
            name='record_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triagesmodel',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='The main employee attending this encounter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='en_triage', to='allifmaalcommonapp.commonemployeesmodel'),
        ),
        migrations.AlterField(
            model_name='triagesmodel',
            name='complaints',
            field=models.TextField(blank=True, help_text="Patient's main symptoms or reason for visit.", null=True),
        ),
        migrations.AlterField(
            model_name='triagesmodel',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Patient's height in centimeters.", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='triagesmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownr_triage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='triagesmodel',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='AssessmentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('complaints', models.TextField(blank=True, help_text="Patient's main symptoms or reason for visit.", null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text="Patient's height in centimeters.", max_digits=10, null=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, help_text='Systolic blood pressure (mmHg).', null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, help_text='Diastolic blood pressure (mmHg).', null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text="Patient's temperature in Celsius.", max_digits=4, null=True)),
                ('pulse_rate', models.IntegerField(blank=True, help_text="Patient's pulse rate (beats per minute).", null=True)),
                ('respiration_rate', models.IntegerField(blank=True, help_text="Patient's respiration rate (breaths per minute).", null=True)),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=1, help_text="Patient's oxygen saturation (SpO2 %).", max_digits=4, null=True)),
                ('past_medical_history', models.TextField(blank=True, help_text='Relevant past medical history provided by the patient.', null=True)),
                ('known_chronic_conditions', models.TextField(blank=True, help_text="Patient's reported chronic conditions at triage.", null=True)),
                ('current_medication', models.TextField(blank=True, help_text='Medications patient is currently taking, reported at triage.', null=True)),
                ('treatment_plan', models.TextField(blank=True, help_text='Treatment plan (medications, tests, referrals, follow-up).', null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnch_assessments', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmp_assessment', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_assessments', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvs_assessment', to='allifmaalcommonapp.commondivisionsmodel')),
                ('medical_file', models.ForeignKey(blank=True, help_text='The customer associated with this encounter.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fileassessemnt', to='allifmaalcommonapp.commontransactionsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownr_assessments', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, help_text='The main employee attending this encounter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='en_assessment', to='allifmaalcommonapp.commonemployeesmodel')),
            ],
        ),
    ]
