# Generated by Django 4.2.20 on 2025-07-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0004_alter_triagesmodel_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
    ]
