# Generated by Django 4.2.20 on 2025-07-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0004_triagesmodel_balance_triagesmodel_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonTestModel',
        ),
    ]
