# Generated by Django 4.2.20 on 2025-08-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0004_alter_labtestrequestsmodel_test_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestresultsmodel',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='labtestresultsmodel',
            name='medical_file',
        ),
        migrations.RemoveField(
            model_name='labtestresultsmodel',
            name='results',
        ),
        migrations.AlterField(
            model_name='labtestresultsmodel',
            name='comments',
            field=models.TextField(blank=True, default='Comments', null=True),
        ),
        migrations.AlterField(
            model_name='labtestresultsmodel',
            name='description',
            field=models.TextField(blank=True, default='Description', null=True),
        ),
    ]
