# Generated by Django 4.2.20 on 2025-06-09 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0026_remove_commonattendancesmodel_course_and_more'),
        ('allifmaalshaafiapp', '0004_alter_prescriptionsmodel_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsmodel',
            name='scheduled_service',
            field=models.ForeignKey(blank=True, help_text='The medical service for which this appointment is scheduled (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_appointments', to='allifmaalcommonapp.commonstockcategoriesmodel'),
        ),
    ]
