# Generated by Django 4.2.20 on 2025-06-23 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0045_delete_commonbookingsmodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalshaafiapp', '0005_remove_triagesmodel_current_medications_at_triage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestRequestsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Type of referral (Internal or External).', max_length=50, null=True)),
                ('date_time', models.DateTimeField(blank=True, help_text='Date and time of patient admission.', null=True)),
                ('status', models.CharField(choices=[('Ordered', 'Ordered'), ('Collected', 'Sample Collected'), ('Processing', 'Under Processing'), ('Completed', 'Completed'), ('Validated', 'Validated'), ('Resulted', 'Results Available'), ('Pending', 'Pending Collection'), ('Cancelled', 'Cancelled'), ('Lost', 'Lost')], default='Pending', help_text='Current status of the lab order.', max_length=50)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Urgent', 'Urgent')], default='Pending', help_text='Current status of the lab order.', max_length=50)),
                ('specimen', models.CharField(choices=[('Blood', 'Blood'), ('Urine', 'Urine'), ('Tissue', 'Tissue'), ('Saliva', 'Saliva'), ('Stool', 'Stool'), ('Other', 'Other')], default='Blood', help_text='Current status of the lab order.', max_length=50)),
                ('comments', models.TextField(blank=True, help_text='Additional instructions or clinical notes for the laboratory.', null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_lab_test_requests', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_lab_test_requests', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_lab_test_requests', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisions_lab_test_requests', to='allifmaalcommonapp.commondivisionsmodel')),
                ('items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_lab_test_requests', to='allifmaalcommonapp.commonstocksmodel')),
                ('lab_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_name_lab_test_requests', to='allifmaalcommonapp.commonspacesmodel')),
                ('medical_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_file_lab_test_requests', to='allifmaalcommonapp.commontransactionsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_lab_test_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabTestResultsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.CharField(blank=True, default='Results', max_length=50, null=True)),
                ('description', models.CharField(blank=True, default='Results', max_length=50, null=True)),
                ('date_time', models.DateTimeField(blank=True, help_text='Date and time of patient admission.', null=True)),
                ('comments', models.TextField(blank=True, help_text='Additional instructions or clinical notes for the laboratory.', null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_lab_test_requests_results', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_lab_test_requests_results', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_lab_test_requests_results', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisions_lab_test_requests_results', to='allifmaalcommonapp.commondivisionsmodel')),
                ('lab_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_name_lab_test_requests_results', to='allifmaalcommonapp.commonspacesmodel')),
                ('medical_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_file_lab_test_requests_results', to='allifmaalcommonapp.commontransactionsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_lab_test_requests_results', to=settings.AUTH_USER_MODEL)),
                ('test_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_lab_test_requests_results', to='allifmaalshaafiapp.labtestrequestsmodel')),
            ],
        ),
    ]
