# Generated by Django 4.2.20 on 2025-07-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0005_delete_commontestmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagesmodel',
            name='code',
            field=models.CharField(blank=True, default='Code', help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='triagesmodel',
            name='number',
            field=models.CharField(blank=True, default='#No', help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True),
        ),
    ]
