# Generated by Django 4.2.20 on 2025-06-09 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0028_remove_commonstockcategoriesmodel_branch_and_more'),
        ('allifmaalshaafiapp', '0005_alter_appointmentsmodel_scheduled_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsmodel',
            name='scheduled_service',
            field=models.ForeignKey(blank=True, help_text='The medical service for which this appointment is scheduled (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_appointments', to='allifmaalcommonapp.commoncategoriesmodel'),
        ),
    ]
