# Generated by Django 4.2.20 on 2025-08-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0005_remove_labtestresultsmodel_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestresultsmodel',
            name='lab_name',
        ),
    ]
