# Generated by Django 4.2.20 on 2025-06-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0006_labtestrequestsmodel_labtestresultsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagesmodel',
            name='allergies',
            field=models.TextField(blank=True, help_text="Patient's reported allergies (e.g., medications, food, environmental).", null=True),
        ),
        migrations.AddField(
            model_name='triagesmodel',
            name='disposition_notes',
            field=models.TextField(blank=True, help_text='Detailed notes on the triage disposition.', null=True),
        ),
        migrations.AddField(
            model_name='triagesmodel',
            name='mental_status',
            field=models.CharField(blank=True, choices=[('ALERT', 'Alert'), ('VERBAL', 'Responds to Verbal Stimuli'), ('PAIN', 'Responds to Painful Stimuli'), ('UNRESPONSIVE', 'Unresponsive')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='triagesmodel',
            name='mobility_status',
            field=models.CharField(blank=True, choices=[('AMBULATORY', 'Ambulatory (Walks independently)'), ('ASSISTED', 'Assisted (Uses crutches, cane, etc.)'), ('WHEELCHAIR', 'Wheelchair Bound'), ('STRETCHER', 'Stretcher/Bedridden')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='triagesmodel',
            name='mode_of_arrival',
            field=models.CharField(blank=True, choices=[('AMBULANCE', 'Ambulance'), ('WALK_IN', 'Walk-in'), ('PRIVATE_VEHICLE', 'Private Vehicle'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='triagesmodel',
            name='pain_level',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text="Patient's reported pain level (0-10, 0=no pain, 10=worst pain).", null=True),
        ),
        migrations.AddField(
            model_name='triagesmodel',
            name='triage_disposition',
            field=models.CharField(blank=True, choices=[('EMERGENCY', 'Emergency/Critical Care'), ('URGENT', 'Urgent Care'), ('NON_URGENT', 'Non-Urgent/Primary Care'), ('REFERRAL', 'Referral to Specialist'), ('DISCHARGE', 'Discharge (after minor first aid)'), ('ADMIT', 'Admit for Observation/Inpatient')], help_text='Triage decision or immediate disposition of the patient.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='triagesmodel',
            name='triage_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Resuscitation (Immediate)'), (2, 'Emergency (High Risk)'), (3, 'Urgent'), (4, 'Less Urgent (Non-Emergency)'), (5, 'Non-Urgent')], help_text='Assigned triage urgency level (e.g., ESI level 1-5).', null=True),
        ),
    ]
