# Generated by Django 4.2.20 on 2025-06-10 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0035_remove_commontransactioneventsmodel_branch_and_more'),
        ('allifmaalshaafiapp', '0006_alter_appointmentsmodel_scheduled_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionsmodel',
            name='medical_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mdcladmnss', to='allifmaalcommonapp.commontransactionsmodel'),
        ),
        migrations.AlterField(
            model_name='medicaladministrationsmodel',
            name='medical_file',
            field=models.ForeignKey(blank=True, help_text='The encounter this medication administration belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to='allifmaalcommonapp.commontransactionsmodel'),
        ),
        migrations.AlterField(
            model_name='nursingnotesmodel',
            name='medical_file',
            field=models.ForeignKey(blank=True, help_text='The encounter this nursing note belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='allifmaalcommonapp.commontransactionsmodel'),
        ),
        migrations.AlterField(
            model_name='prescriptionsmodel',
            name='medical_file',
            field=models.ForeignKey(blank=True, help_text='The encounter this prescription belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='allifmaalcommonapp.commontransactionsmodel'),
        ),
        migrations.AlterField(
            model_name='referralsmodel',
            name='medical_file',
            field=models.ForeignKey(blank=True, help_text='The encounter this referral belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_medfile', to='allifmaalcommonapp.commontransactionsmodel'),
        ),
        migrations.AlterField(
            model_name='vitalsignsmodel',
            name='medical_file',
            field=models.ForeignKey(blank=True, help_text='The encounter this vital signs record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='allifmaalcommonapp.commontransactionsmodel'),
        ),
    ]
