# Generated by Django 4.2.20 on 2025-08-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0006_remove_labtestresultsmodel_lab_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionsmodel',
            name='admission_date_time',
        ),
        migrations.RemoveField(
            model_name='admissionsmodel',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='admissionsmodel',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='admissionsmodel',
            name='reason_for_admission',
        ),
        migrations.AlterField(
            model_name='admissionsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
    ]
