# Generated by Django 4.2.20 on 2025-07-03 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalshaafiapp', '0006_alter_triagesmodel_code_alter_triagesmodel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagesmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownr_triages', to=settings.AUTH_USER_MODEL),
        ),
    ]
