# Generated by Django 4.2.20 on 2025-08-08 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0006_alter_commonbranchesmodel_can_delete_and_more'),
        ('allifmaalshaafiapp', '0007_remove_admissionsmodel_admission_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargesmodel',
            name='medical_file',
            field=models.ForeignKey(blank=True, help_text='The encounter this medication administration belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishargeAddmission', to='allifmaalcommonapp.commontransactionsmodel'),
        ),
    ]
