# Generated by Django 4.2.20 on 2025-06-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0007_triagesmodel_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagesmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
