# Generated by Django 4.2.20 on 2025-06-13 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0056_alter_commonspacesmodel_branch_and_more'),
        ('allifmaalshaafiapp', '0007_alter_admissionsmodel_medical_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionsmodel',
            name='patient',
        ),
        migrations.AlterField(
            model_name='admissionsmodel',
            name='ward',
            field=models.ForeignKey(blank=True, help_text='The ward to which the patient is admitted.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='allifmaalcommonapp.commonspacesmodel'),
        ),
        migrations.AlterField(
            model_name='bedsmodel',
            name='ward',
            field=models.ForeignKey(blank=True, help_text='The ward to which this bed belongs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bedsword', to='allifmaalcommonapp.commonspacesmodel'),
        ),
        migrations.DeleteModel(
            name='WardsModel',
        ),
    ]
