# Generated by Django 4.2.20 on 2025-06-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0008_triagesmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagesmodel',
            name='mental_status',
            field=models.CharField(blank=True, choices=[('Alert', 'Alert and Aware'), ('Disoriented', 'Disoriented'), ('Drowsy', 'Drowsy'), ('Responds_to_voice', 'Responds to Voice'), ('Responds_to_pain', 'Responds to Pain'), ('Agitated', 'Agitated / Restless'), ('Combative', 'Combative / Aggressive'), ('Withdrawn', 'Withdrawn / Very Quiet'), ('Unresponsive', 'Completely Unresponsive'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='triagesmodel',
            name='mobility_status',
            field=models.CharField(blank=True, choices=[('Walking', 'Walking'), ('Assisted', 'Assisted'), ('Wheelchair', 'Wheelchaired'), ('Stretcher', 'Stretcher')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='triagesmodel',
            name='mode_of_arrival',
            field=models.CharField(blank=True, choices=[('Ambulance', 'Ambulance'), ('Walk-in', 'Walk-in'), ('Vehicle', 'Vehicle'), ('Aeroplane', 'Aeroplane'), ('Wheelchair', 'Wheelchair'), ('Police', 'Police'), ('Stretcher', 'Stretcher'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='triagesmodel',
            name='triage_disposition',
            field=models.CharField(blank=True, choices=[('Emergency', 'Emergency/Critical Care'), ('Urgent', 'Urgent Care'), ('Normal', 'Normal'), ('Referral', 'Referral to Specialist'), ('Discharge', 'Discharge'), ('Admit', 'Admission')], help_text='Triage decision or immediate disposition of the patient.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='triagesmodel',
            name='triage_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Resuscitation'), (2, 'Emergency'), (3, 'Urgent'), (4, 'Normal')], help_text='Assigned triage urgency level (e.g., ESI level 1-5).', null=True),
        ),
    ]
