# Generated by Django 4.2.20 on 2025-08-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0008_dischargesmodel_medical_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dischargesmodel',
            name='recorded_on',
        ),
        migrations.AlterField(
            model_name='referralsmodel',
            name='referral_type',
            field=models.CharField(blank=True, choices=[('INT', 'Internal'), ('EXT', 'External')], default='INT', help_text='Type of referral (Internal or External).', max_length=10, null=True),
        ),
    ]
