# Generated by Django 4.2.20 on 2025-06-13 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0057_commonprogressmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalshaafiapp', '0008_remove_prescriptionsmodel_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage_form', models.CharField(blank=True, choices=[('TAB', 'Tablet'), ('SYR', 'Syrup'), ('CAP', 'Capsule'), ('INJ', 'Injection'), ('CREAM', 'Cream'), ('DROPS', 'Drops'), ('OTH', 'Other')], default='Please select', help_text='Formulation of the drug (e.g., Tablet, Syrup, Injection).', max_length=200, null=True)),
                ('dosage', models.CharField(blank=True, choices=[('MG', 'Milligrams'), ('G', 'Grams'), ('ML', 'Milliliters'), ('UNIT', 'Units'), ('PIECE', 'Pieces'), ('DROP', 'Drops'), ('MCG', 'Micrograms')], help_text="Dosage amount and unit (e.g., '500mg', '10ml').", max_length=250, null=True)),
                ('route_of_administration', models.CharField(blank=True, choices=[('ORAL', 'Oral'), ('IM', 'Intramuscular Injection'), ('IV', 'Intravenous Injection'), ('INHAL', 'Inhalation'), ('TOPIC', 'Topical'), ('SUBQ', 'Subcutaneous')], default='ORAL', help_text='How the medication should be administered (e.g., Oral, IV, IM).', max_length=250, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=30, null=True)),
                ('is_issued', models.BooleanField(default=False, help_text='True if the prescription has been dispensed by the pharmacy.', max_length=50)),
                ('frequency', models.CharField(blank=True, help_text="How often the medication should be taken (e.g., 'Once daily', 'Twice a day').", max_length=100, null=True)),
                ('duration', models.CharField(blank=True, help_text="Duration of the treatment (e.g., '7 days', 'Until finished').", max_length=100, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Patient-specific instructions for medication use.', null=True)),
                ('issued_date_time', models.DateTimeField(blank=True, help_text='Date and time when the prescription was dispensed.', null=True)),
                ('prescription_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchprescrptn', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmpprescrptns', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptprescrptns', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsprescrptns', to='allifmaalcommonapp.commondivisionsmodel')),
                ('issued_by_pharmacist', models.ForeignKey(blank=True, help_text='The pharmacist who dispensed the medication (if dispensed).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to='allifmaalcommonapp.commonemployeesmodel')),
                ('medical_file', models.ForeignKey(blank=True, help_text='The encounter this prescription belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='allifmaalcommonapp.commontransactionsmodel')),
                ('medication', models.ForeignKey(blank=True, help_text='The drug/item prescribed (from common inventory).', max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='allifmaalcommonapp.commonstocksmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownrprescrptns', to=settings.AUTH_USER_MODEL)),
                ('prescribed_by_doctor', models.ForeignKey(blank=True, help_text='The doctor who issued this prescription.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_prescriptions', to='allifmaalcommonapp.commonemployeesmodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='bedsmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='bedsmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='bedsmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='bedsmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='bedsmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='bedsmodel',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='prescriptionsmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='prescriptionsmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='prescriptionsmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='prescriptionsmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='prescriptionsmodel',
            name='issued_by_pharmacist',
        ),
        migrations.RemoveField(
            model_name='prescriptionsmodel',
            name='medical_file',
        ),
        migrations.RemoveField(
            model_name='prescriptionsmodel',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='prescriptionsmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='prescriptionsmodel',
            name='prescribed_by_doctor',
        ),
        migrations.RemoveField(
            model_name='vitalsignsmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='vitalsignsmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vitalsignsmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='vitalsignsmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='vitalsignsmodel',
            name='medical_file',
        ),
        migrations.RemoveField(
            model_name='vitalsignsmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='vitalsignsmodel',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='vitalsignsmodel',
            name='recorded_by_nurse',
        ),
        migrations.RemoveField(
            model_name='admissionsmodel',
            name='patient',
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='description',
            field=models.CharField(blank=True, help_text='Type of referral (Internal or External).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admissionsmodel',
            name='bed',
            field=models.ForeignKey(blank=True, help_text='The specific bed allocated to the patient.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='allifmaalcommonapp.commonspaceunitsmodel'),
        ),
        migrations.DeleteModel(
            name='AppointmentsModel',
        ),
        migrations.DeleteModel(
            name='BedsModel',
        ),
        migrations.DeleteModel(
            name='VitalSignsModel',
        ),
        migrations.AlterField(
            model_name='medicaladministrationsmodel',
            name='prescription',
            field=models.ForeignKey(blank=True, help_text='The prescription being administered (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrations', to='allifmaalshaafiapp.medicationsmodel'),
        ),
        migrations.DeleteModel(
            name='PrescriptionsModel',
        ),
    ]
