# Generated by Django 4.2.20 on 2025-06-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0009_alter_triagesmodel_mental_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestrequestsmodel',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Urgent', 'Urgent')], default='Pending', help_text='Current status of the lab order.', max_length=50),
        ),
    ]
