# Generated by Django 4.2.20 on 2025-06-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0009_medicationsmodel_remove_bedsmodel_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dischargesummarymodel',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='medicaladministrationsmodel',
            name='drug_name',
        ),
        migrations.RemoveField(
            model_name='medicaladministrationsmodel',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='medicaladministrationsmodel',
            name='route_of_administration',
        ),
        migrations.RemoveField(
            model_name='medicationsmodel',
            name='route_of_administration',
        ),
        migrations.RemoveField(
            model_name='referralsmodel',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='referralsmodel',
            name='referred_to_department',
        ),
        migrations.AddField(
            model_name='medicaladministrationsmodel',
            name='via',
            field=models.CharField(blank=True, choices=[('ORAL', 'Oral'), ('IM', 'Intramuscular Injection'), ('IV', 'Intravenous Injection'), ('INHAL', 'Inhalation'), ('TOPIC', 'Topical'), ('SUBQ', 'Subcutaneous')], help_text='The route by which the medication was administered.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicationsmodel',
            name='via',
            field=models.CharField(blank=True, choices=[('ORAL', 'Oral'), ('IM', 'Intramuscular Injection'), ('IV', 'Intravenous Injection'), ('INHAL', 'Inhalation'), ('TOPIC', 'Topical'), ('SUBQ', 'Subcutaneous')], default='ORAL', help_text='How the medication should be administered (e.g., Oral, IV, IM).', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='medicationsmodel',
            name='duration',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='medicationsmodel',
            name='frequency',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='referralsmodel',
            name='referred_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='NursingNotesModel',
        ),
    ]
