# Generated by Django 4.2.20 on 2025-08-08 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0006_alter_commonbranchesmodel_can_delete_and_more'),
        ('allifmaalshaafiapp', '0009_remove_dischargesmodel_recorded_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestrequestsmodel',
            name='medical_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_file_lab_test_requests', to='allifmaalcommonapp.commontransactionsmodel'),
        ),
    ]
