# Generated by Django 4.2.20 on 2025-08-08 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0010_alter_labtestrequestsmodel_medical_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestresultsmodel',
            name='test_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_lab_test_requests_results', to='allifmaalshaafiapp.labtestrequestsmodel'),
        ),
    ]
