# Generated by Django 4.2.20 on 2025-06-13 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0057_commonprogressmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalshaafiapp', '0010_remove_dischargesummarymodel_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_summary', models.CharField(blank=True, max_length=250, null=True)),
                ('discharge_diagnosis', models.CharField(blank=True, max_length=250, null=True)),
                ('medications_at_discharge', models.CharField(blank=True, max_length=250, null=True)),
                ('follow_up_plan', models.CharField(blank=True, max_length=250, null=True)),
                ('recorded_on', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dschrgsummryadmsn', to='allifmaalshaafiapp.admissionsmodel')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_nursing_notes', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_nursing_notes', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_nursing_notes', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_nursing_notes', to='allifmaalcommonapp.commondivisionsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_nursing_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DischargeSummaryModel',
        ),
    ]
