# Generated by Django 4.2.20 on 2025-08-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0011_alter_labtestresultsmodel_test_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationsmodel',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='medicationsmodel',
            name='issued_date_time',
        ),
        migrations.RemoveField(
            model_name='medicationsmodel',
            name='prescription_date_time',
        ),
    ]
