# Generated by Django 4.2.20 on 2025-06-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0011_dischargesmodel_delete_dischargesummarymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionsmodel',
            name='discharge_reason',
        ),
    ]
