# Generated by Django 4.2.20 on 2025-06-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0012_remove_admissionsmodel_discharge_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionsmodel',
            name='discharge_date_time',
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time of patient admission.', null=True),
        ),
        migrations.AlterField(
            model_name='admissionsmodel',
            name='admission_date_time',
            field=models.DateTimeField(blank=True, help_text='Date and time of patient discharge (if applicable).', null=True),
        ),
    ]
