# Generated by Django 4.2.20 on 2025-08-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0012_remove_medicationsmodel_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaladministrationsmodel',
            name='medical_file',
        ),
    ]
