# Generated by Django 4.2.20 on 2025-08-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalshaafiapp', '0013_remove_medicaladministrationsmodel_medical_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dischargesmodel',
            name='medical_file',
        ),
        migrations.RemoveField(
            model_name='referralsmodel',
            name='reason_for_referral',
        ),
        migrations.RemoveField(
            model_name='referralsmodel',
            name='referral_date_time',
        ),
        migrations.RemoveField(
            model_name='referralsmodel',
            name='referred_on',
        ),
        migrations.AlterField(
            model_name='referralsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
    ]
