# Generated by Django 4.2.20 on 2025-08-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalusersapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userbranch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userdepartment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userdivision',
        ),
    ]
