# Generated by Django 4.2.20 on 2025-06-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalusersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customurlslug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='url_unique_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_category',
            field=models.CharField(blank=True, choices=[('owner', 'owner'), ('chairman', 'chairman'), ('ceo', 'ceo'), ('director', 'director'), ('genmanager', 'genmanager'), ('admin', 'admin'), ('staff', 'staff'), ('guest', 'guest')], default='guest', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userbranch',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='usercompany',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userdepartment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userdivision',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
