# Generated by Django 5.1.5 on 2025-02-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalusersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullNamesdff',
            field=models.CharField(blank=True, default='User Full Namesdsfds', max_length=255, null=True),
        ),
    ]
