# Generated by Django 4.2.20 on 2025-08-29 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalusersapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='peformance_counter',
            new_name='performance_counter',
        ),
    ]
