# Generated by Django 5.1.5 on 2025-02-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalusersapp', '0002_user_fullnamesdff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fullNamesdff',
        ),
    ]
