# Generated by Django 5.1.5 on 2025-02-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalusersapp', '0003_remove_user_fullnamesdff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullNamessss',
            field=models.CharField(blank=True, default='User Full Names', max_length=255, null=True),
        ),
    ]
