# Generated by Django 4.2.20 on 2025-08-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalusersapp', '0003_user_branch_user_department_user_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usercompany',
        ),
    ]
