# Generated by Django 4.2.20 on 2025-04-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalusersapp', '0005_remove_user_fullnamessss'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch_delete',
            field=models.BooleanField(default=False, verbose_name='Can delete anything in the branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='divisional_delete',
            field=models.BooleanField(default=False, verbose_name='Can delete anything in their division'),
        ),
        migrations.AddField(
            model_name='user',
            name='universal_delete',
            field=models.BooleanField(default=False, verbose_name='Can delete anything in the company'),
        ),
    ]
