# Generated by Django 4.2.20 on 2025-04-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalusersapp', '0006_user_branch_delete_user_divisional_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch_access',
            field=models.BooleanField(default=False, verbose_name='Can access anything in the branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='department_delete',
            field=models.BooleanField(default=False, verbose_name='Can delete anything in the department'),
        ),
        migrations.AddField(
            model_name='user',
            name='departmental_access',
            field=models.BooleanField(default=False, verbose_name='Can access anything in the department'),
        ),
        migrations.AddField(
            model_name='user',
            name='divisional_access',
            field=models.BooleanField(default=False, verbose_name='Can access anything in their division'),
        ),
        migrations.AddField(
            model_name='user',
            name='universal_access',
            field=models.BooleanField(default=False, verbose_name='Can access anything in the company'),
        ),
    ]
