# Generated by Django 4.2.20 on 2025-04-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalusersapp', '0007_user_branch_access_user_department_delete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='department_delete',
            new_name='departmental_delete',
        ),
    ]
