# Generated by Django 4.2.20 on 2025-04-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalusersapp', '0008_rename_department_delete_user_departmental_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='branch_access',
            new_name='branches_access',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='branch_delete',
            new_name='branches_delete',
        ),
    ]
