# Generated by Django 4.2.20 on 2025-07-31 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allifmaalcommonapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Name', max_length=50, null=True)),
                ('number', models.CharField(blank=True, default='#No', help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField(blank=True, default='Description', null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('comments', models.TextField(blank=True, default='Comments', null=True)),
                ('starts', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ends', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(blank=True, default='Code', help_text='Unique code for the program, e.g., BSCIT', max_length=50, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True)),
                ('priority', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Urgent', 'Urgent')], default='Normal', max_length=50, null=True)),
                ('delete_status', models.CharField(blank=True, choices=[('Undeletable', 'Undeletable'), ('Deletable', 'Deletable')], default='Deletable', max_length=30, null=True)),
                ('uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('reference', models.CharField(blank=True, db_index=True, default='reference', help_text='An optional identifier from an external system or an internal reference code.', max_length=100, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondivisionsmodel')),
                ('flights', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='allifmaalcommonapp.commontransitmodel')),
                ('operation_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='allifmaalcommonapp.commonoperationyeartermsmodel')),
                ('operation_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='allifmaalcommonapp.commonoperationyearsmodel')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
    ]
