# Generated by Django 4.2.20 on 2025-09-06 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allifmaalcommonapp', '0001_initial'),
        ('allifmaallogisticsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketsmodel',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passengers', to='allifmaalcommonapp.commoncustomersmodel'),
        ),
        migrations.AddField(
            model_name='ticketsmodel',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_payment_mode_tickets', to='allifmaalcommonapp.commonpaymenttermsmodel'),
        ),
        migrations.AddField(
            model_name='ticketsmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flightsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='flightsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='flightsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='flightsmodel',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_code', to='allifmaalcommonapp.commoncodesmodel'),
        ),
        migrations.AddField(
            model_name='flightsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='flightsmodel',
            name='operation_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonoperationyeartermsmodel'),
        ),
        migrations.AddField(
            model_name='flightsmodel',
            name='operation_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonoperationyearsmodel'),
        ),
        migrations.AddField(
            model_name='flightsmodel',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_code', to='allifmaalcommonapp.commoncodesmodel'),
        ),
        migrations.AddField(
            model_name='flightsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flightsmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
