# Generated by Django 4.2.20 on 2025-09-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaallogisticsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsmodel',
            name='flight_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='flightsmodel',
            name='seats_available',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='flightsmodel',
            name='seats_booked',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='flightsmodel',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='flightsmodel',
            name='ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticketsmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticketsmodel',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticketsmodel',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True),
        ),
    ]
