# Generated by Django 4.2.20 on 2025-06-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0002_alter_commonwarehousesmodel_company'),
        ('allifmaallogisticsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airports_company_relname', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
    ]
