# Generated by Django 4.2.20 on 2025-09-12 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0003_commoncarriersmodel'),
        ('allifmaallogisticsapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsmodel',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_carrier', to='allifmaalcommonapp.commoncarriersmodel'),
        ),
    ]
