# Generated by Django 4.2.20 on 2025-08-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaallogisticsapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengersmodel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
    ]
