# Generated by Django 4.2.20 on 2025-06-09 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaallogisticsapp', '0002_alter_airportsmodel_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airports_owners', to=settings.AUTH_USER_MODEL),
        ),
    ]
