# Generated by Django 4.2.20 on 2025-09-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaallogisticsapp', '0003_alter_flightsmodel_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightsmodel',
            name='via',
            field=models.CharField(blank=True, default='N/A', max_length=250, null=True),
        ),
    ]
