# Generated by Django 4.2.20 on 2025-06-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaallogisticsapp', '0003_alter_airportsmodel_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('airport_name', models.CharField(blank=True, max_length=100, null=True)),
                ('airport_code', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='airportsmodel',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
