# Generated by Django 4.2.20 on 2025-08-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaallogisticsapp', '0003_passengersmodel_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengersmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Waiting', 'Waiting'), ('Emergency', 'Emergency'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Active', max_length=50, null=True),
        ),
    ]
