# Generated by Django 4.2.20 on 2025-06-13 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0052_alter_commontransitmodel_delivery_notes'),
        ('allifmaallogisticsapp', '0004_flightitemsmodel_airportsmodel_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlightItemsModel',
        ),
        migrations.AddField(
            model_name='flightsmodel',
            name='transit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transits_owners', to='allifmaalcommonapp.commontransitmodel'),
        ),
    ]
