# Generated by Django 4.2.20 on 2025-06-13 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0054_commoncodesmodel'),
        ('allifmaallogisticsapp', '0005_delete_flightitemsmodel_flightsmodel_transit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightsmodel',
            name='flight_destination',
        ),
        migrations.RemoveField(
            model_name='flightsmodel',
            name='flight_origin',
        ),
        migrations.RemoveField(
            model_name='flightsmodel',
            name='transit',
        ),
        migrations.AlterField(
            model_name='passengersmodel',
            name='flights',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='allifmaalcommonapp.commontransitmodel'),
        ),
        migrations.DeleteModel(
            name='AirportsModel',
        ),
        migrations.DeleteModel(
            name='FlightsModel',
        ),
    ]
