# Generated by Django 4.2.20 on 2025-06-14 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allifmaalcommonapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonClassesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('comments', models.CharField(blank=True, default='comment', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonFormsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('comments', models.CharField(blank=True, default='comment', max_length=30, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchforms', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmnfrmcmp', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptforms', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsforms', to='allifmaalcommonapp.commondivisionsmodel')),
            ],
        ),
    ]
