# Generated by Django 4.2.20 on 2025-06-14 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allifmaalilmapp', '0001_initial'),
        ('allifmaalcommonapp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commonformsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnusfrm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonclassesmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brnchclss', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='commonclassesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnclscmpy', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='commonclassesmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dptclss', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='commonclassesmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvsclsss', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='commonclassesmodel',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allifmaalilmapp.commonformsmodel'),
        ),
        migrations.AddField(
            model_name='commonclassesmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnusrclsrln', to=settings.AUTH_USER_MODEL),
        ),
    ]
