# Generated by Django 4.2.20 on 2025-08-02 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allifmaalilmapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalcommonapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresultsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examresultsmodel',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allifmaalilmapp.examinationsmodel'),
        ),
        migrations.AddField(
            model_name='examresultsmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examinationsmodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commonbranchesmodel'),
        ),
        migrations.AddField(
            model_name='examinationsmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='allifmaalcommonapp.commoncompanydetailsmodel'),
        ),
        migrations.AddField(
            model_name='examinationsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondepartmentsmodel'),
        ),
        migrations.AddField(
            model_name='examinationsmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='allifmaalcommonapp.commondivisionsmodel'),
        ),
        migrations.AddField(
            model_name='examinationsmodel',
            name='exam_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_education_exams', to='allifmaalcommonapp.commontransactionsmodel'),
        ),
        migrations.AddField(
            model_name='examinationsmodel',
            name='operation_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='allifmaalcommonapp.commonoperationyeartermsmodel'),
        ),
        migrations.AddField(
            model_name='examinationsmodel',
            name='operation_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='allifmaalcommonapp.commonoperationyearsmodel'),
        ),
        migrations.AddField(
            model_name='examinationsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examinationsmodel',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_education_exams', to='allifmaalcommonapp.commonstocksmodel'),
        ),
        migrations.AddField(
            model_name='examinationsmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
