# Generated by Django 4.2.20 on 2025-06-23 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalcommonapp', '0045_delete_commonbookingsmodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allifmaalilmapp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.CharField(blank=True, default='comment', max_length=30, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('exam_date', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_exams', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_exams', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_exams', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_exams', to='allifmaalcommonapp.commondivisionsmodel')),
                ('exam_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_education_exams', to='allifmaalcommonapp.commontransactionsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_exams', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_education_exams', to='allifmaalcommonapp.commonstocksmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResultsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.CharField(blank=True, default='comment', max_length=30, null=True)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('result_date', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_exam_results', to='allifmaalcommonapp.commonbranchesmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_exam_results', to='allifmaalcommonapp.commoncompanydetailsmodel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dpt_exam_results', to='allifmaalcommonapp.commondepartmentsmodel')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divison_exam_results', to='allifmaalcommonapp.commondivisionsmodel')),
                ('exam_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_file_education_exams_results', to='allifmaalcommonapp.commontransactionsmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_exam_results', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allifmaalilmapp.examinationsmodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='commonformsmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commonformsmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='commonformsmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='commonformsmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonformsmodel',
            name='owner',
        ),
        migrations.DeleteModel(
            name='CommonClassesModel',
        ),
        migrations.DeleteModel(
            name='CommonFormsModel',
        ),
    ]
